# -*- coding: utf-8 -*-
"""人教版（2024 新教材）初中一年级上册英语全部单元交互自测题生成脚本。"""
import random

from _quizlib import S, S2, M, run


RNG = random.Random(20261201)


def _others(correct, pool, n=3):
    xs = [x for x in pool if x != correct]
    RNG.shuffle(xs)
    return xs[:n]


def en2cn(en, cn, pool_cn):
    return ("s", "「%s」的意思是（　）。" % en, [cn] + _others(cn, pool_cn), ["A"])


def cn2en(cn, en, pool_en):
    return ("s", "「%s」用英语说是（　）。" % cn, [en] + _others(en, pool_en), ["A"])


def first_letter(en, pool_letters):
    answer = en[0].upper()
    return ("s", "单词或短语「%s」的第一个字母是（　）。" % en,
            [answer] + _others(answer, pool_letters), ["A"])


def letter_case(letter):
    up, low = letter.upper(), letter.lower()
    return ("s", "大写字母「%s」的小写形式是（　）。" % up,
            [low, up, chr((ord(low) - 97 + 1) % 26 + 97),
             chr((ord(low) - 97 + 2) % 26 + 97)], ["A"])


def build_vocab(words, want=22):
    """词汇课：英译中 + 中译英 + 首字母 + 大小写。"""
    pool_cn = [cn for _, cn in words]
    pool_en = [en for en, _ in words]
    letters = list("ABCDEFGHIJKLMNOPQRSTW")
    questions = []
    for en, cn in words:
        questions.append(en2cn(en, cn, pool_cn))
        questions.append(cn2en(cn, en, pool_en))
        if len(en) >= 3:
            questions.append(first_letter(en, letters))
    for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
        questions.append(letter_case(letter))
    seen, result = set(), []
    for question in questions:
        if question[1] in seen:
            continue
        seen.add(question[1])
        result.append(question)
    RNG.shuffle(result)
    return result[:want]


def Q(stem, ans, *wrong):
    return S(stem, ans, [str(item) for item in wrong])


UNITS = [
    ("第一单元 Starter 起始单元", [
        ("第1课 字母与问候", "Letters Aa-Zz and greetings: Hello! Good morning! How are you? 学会打招呼和自我介绍。", build_vocab([
            ("hello", "你好"), ("morning", "早晨"), ("afternoon", "下午"),
            ("evening", "晚上"), ("goodbye", "再见"), ("teacher", "老师"),
            ("student", "学生"), ("friend", "朋友"), ("name", "名字"),
            ("school", "学校"), ("class", "班级"), ("welcome", "欢迎"),
        ])),
        ("第2课 句型与对话", "Sentences: What's your name? / My name is ... / Nice to meet you! / How are you? 学会介绍自己、结识新同学。", [
            Q("询问对方叫什么名字，应该说（　）。", "What's your name?", "Who are you name?", "How is your name?", "Where is your name?"),
            Q("回答 What's your name? 可以说（　）。", "My name is Mike.", "I'm fine, thanks.", "Yes, I am.", "It's a name."),
            Q("初次见面表达“很高兴认识你”说（　）。", "Nice to meet you!", "Nice to meet again!", "How do you meet?", "Meet you next time!"),
            Q("回答 Nice to meet you! 应该说（　）。", "Nice to meet you, too!", "Thank you very much.", "I'm fine, too.", "You're right."),
            Q("“How are you?”是询问（　）。", "对方近况", "对方姓名", "对方年龄", "对方学校"),
            Q("回答 How are you? 可以说（　）。", "I'm fine, thank you.", "How are you again?", "My name is Jack.", "Nice to meet you."),
            Q("“Good morning!”用于（　）。", "早上见面问好", "晚上道别", "道谢", "道歉"),
            Q("自我介绍“我是一名学生”应该说（　）。", "I am a student.", "I am a teacher.", "You are a student.", "He is a student."),
            Q("“This is my friend, Mary.”的意思是（　）。", "这是我的朋友玛丽。", "玛丽是我的老师。", "我认识玛丽。", "玛丽，这是朋友。"),
            Q("听到别人介绍新朋友时可以说（　）。", "Nice to meet you.", "Where is he from?", "How old is he?", "What's his job?"),
            Q("想询问别人“你来自哪里？”应该说（　）。", "Where are you from?", "What are you from?", "Who are you from?", "When are you from?"),
            Q("回答 I'm from China. 的意思是（　）。", "我来自中国。", "我在中国。", "我去中国。", "我喜欢中国。"),
            Q("“Welcome to our school!”的意思是（　）。", "欢迎来到我们学校！", "我们的学校很好。", "学校欢迎你们回家。", "学校在哪里？"),
            Q("与同学道别时说（　）。", "Goodbye! See you!", "Hello! Good!", "Fine, thank you!", "You're welcome!"),
            Q("“How do you spell it?”是询问（　）。", "怎么拼写", "什么意思", "怎么读", "在哪里"),
            Q("别人帮了你，应该说（　）。", "Thank you.", "I'm sorry.", "Goodbye.", "You're welcome."),
            Q("回答 Thank you. 可以说（　）。", "You're welcome.", "Thank you, too.", "I'm fine.", "See you."),
            Q("“My name is Gina.”也可以说（　）。", "I'm Gina.", "She is Gina.", "This is Gina.", "You are Gina."),
            Q("想认识新同学，可以说（　）。", "May I have your name?", "What do you do?", "How do you do it?", "Do you know me?"),
            Q("“This is Ms Gao.”是（　）的句型。", "介绍他人", "询问他人", "告别", "道谢"),
            Q("英语中名字一般分为名与（　）。", "姓", "号", "字", "称"),
            Q("见面时如果想询问对方的年龄，可以说（　）。", "How old are you?", "What age is yours?", "When old are you?", "Which age are you?"),
        ]),
    ]),
    ("第二单元 You and Me", [
        ("第1课 核心词汇", "Today's words: classmate / full name / last name / grade / country / city。学会介绍自己与他人的基本信息。", build_vocab([
            ("classmate", "同班同学"), ("full name", "全名"), ("last name", "姓氏"),
            ("first name", "名字"), ("grade", "年级"), ("country", "国家"),
            ("city", "城市"), ("hobby", "爱好"), ("favourite", "最喜欢的"),
            ("singer", "歌手"), ("basketball", "篮球"), ("music", "音乐"),
        ])),
        ("第2课 句型与对话", "Sentences: What's your last name? / Where are you from? / How old are you? 学会询问与介绍基本信息。", [
            Q("询问对方的姓，应该说（　）。", "What's your last name?", "What's your family at?", "Who is your last name?", "Where is your last name?"),
            Q("Emma Green 中，last name 是（　）。", "Green", "Emma", "Emma Green", "Mr Green"),
            Q("询问年龄的问句是（　）。", "How old are you?", "How many are you?", "What old is it?", "How old is she from?"),
            Q("“I'm thirteen years old.”的意思是（　）。", "我十三岁。", "我十三班。", "我有十三岁半。", "我在十三岁。"),
            Q("询问对方来自哪个国家，应说（　）。", "What country are you from?", "Which country you from?", "Where country are you?", "Who country are you from?"),
            Q("“She is from the UK.”的意思是（　）。", "她来自英国。", "她喜欢英国。", "她去英国了。", "她在英国工作。"),
            Q("询问对方爱好，可以说（　）。", "What's your hobby?", "Who is your hobby?", "Where is your hobby?", "How is your hobby?"),
            Q("回答爱好可以说（　）。", "I like playing basketball.", "I am basketball.", "You like basketball?", "Basketball is he."),
            Q("“favourite”的意思是（　）。", "最喜欢的", "正确的", "新的", "困难的"),
            Q("询问“你的电话号码是多少？”应说（　）。", "What's your phone number?", "How many your phone?", "Where is your phone number?", "Who's your phone number?"),
            Q("数字“13”的正确拼写是（　）。", "thirteen", "thirty", "threeteen", "thirten"),
            Q("数字“15”的正确拼写是（　）。", "fifteen", "fifty", "fiveteen", "fiften"),
            Q("“classmate”指的是（　）。", "同班同学", "家里人", "老师", "邻居"),
            Q("介绍自己的班级可以说（　）。", "I'm in Class 3, Grade 7.", "I'm Class 3 and Grade 7.", "I at Class 3 Grade 7.", "Me is Class 3."),
            Q("“Nice to meet you.”的应答是（　）。", "Nice to meet you, too.", "And you?", "Fine, thank you.", "You're fine."),
            Q("询问“你在几班？”可以说（　）。", "What class are you in?", "Which class are you at?", "Where class are you?", "How class are you?"),
            Q("“He is my new classmate.”的意思是（　）。", "他是我的新同学。", "他是我的新老师。", "他认识新同学。", "他想去新学校。"),
            Q("自我介绍时可以先说（　）。", "Hello, everyone. My name is ...", "Goodbye, everyone.", "Thank you, everyone.", "You're welcome."),
            Q("“Where do you live?”的意思是（　）。", "你住在哪里？", "你从哪里来？", "你要去哪里？", "你在做什么？"),
            Q("回答住址可以说（　）。", "I live in Beijing.", "I am Beijing.", "I from Beijing.", "I live Beijing in."),
            Q("询问“你会说英语吗？”应说（　）。", "Can you speak English?", "Are you speak English?", "Is English you speak?", "Do you English speak?"),
            Q("“She is my English teacher.”中 teacher 的意思是（　）。", "老师", "学生", "同学", "父母"),
        ]),
        ("第3课 综合运用", "Introduce yourself: name, age, hometown, hobbies. 综合运用本单元内容完成自我介绍。", [
            Q("完整的自我介绍通常不包括（　）。", "同学的银行密码", "姓名", "年龄", "爱好"),
            Q("“I'm Wang Lei. Lei is my first name.”说明（　）。", "Lei 是他的名字", "Lei 是他的姓", "他姓 Lei", "他没有姓"),
            Q("下列问候语用于晚上的是（　）。", "Good evening!", "Good morning!", "Good afternoon!", "Good night!"),
            Q("“How old is your sister?”的正确答句是（　）。", "She is ten.", "He is ten.", "It is ten.", "I am ten."),
            Q("“Where is he from?”中 he 指（　）。", "他", "她", "它", "你"),
            Q("想把朋友介绍给别人，应该说（　）。", "This is my friend.", "He are my friend.", "That friend is me.", "My friend is there."),
            Q("询问“你们班有多少学生？”应说（　）。", "How many students are there in your class?", "How much students in your class?", "What students in your class?", "Who many students?"),
            Q("“There are forty-five students.”的意思是（　）。", "有四十五名学生。", "有四十五个班。", "第四十五个学生。", "学生四十五岁了。"),
            Q("自我介绍里说爱好，常用句型是（　）。", "I like + 名词/动名词", "I am like", "I liking", "Me like"),
            Q("“My favourite colour is blue.”的意思是（　）。", "我最喜欢的颜色是蓝色。", "蓝色是我的衣服。", "我喜欢天蓝色。", "蓝色是蓝色的。"),
            Q("下列属于问路/学校的正确表达是（　）。", "Which school are you in?", "Which school you in?", "Where school you are?", "How school are you?"),
            Q("回答 Which school are you in? 可以说（　）。", "I'm in No. 1 Middle School.", "I'm No.1 Middle School.", "I at No.1 Middle School.", "Me school is one."),
            Q("“May I know your name?”的意思是（　）。", "我可以知道你的名字吗？", "你知道我的名字吗？", "你的名字很长吗？", "我要改名字吗？"),
            Q("“What grade are you in?”的正确回答是（　）。", "I'm in Grade Seven.", "I'm Grade Seven in.", "Seven Grade I'm.", "Grade me seven."),
            Q("数字 20 的正确拼写是（　）。", "twenty", "twelve", "twenteen", "twenty-one"),
            Q("数字 12 的正确拼写是（　）。", "twelve", "twenty", "twelf", "twoten"),
            Q("“We are in the same class.”的意思是（　）。", "我们在同一个班。", "我们在同一个学校。", "我们同一个国家。", "我们同一个年级。"),
            Q("听到别人的自我介绍后，礼貌回应可以说（　）。", "Nice to know you.", "That's OK.", "It doesn't matter.", "Never mind."),
            Q("下列哪项是询问职业的表达？（　）。", "What do you do?", "How do you do?", "What are you doing?", "Who do you do?"),
            Q("“I want to make friends with you.”的意思是（　）。", "我想和你交朋友。", "我有很多朋友。", "我和你一样。", "你是我朋友吗？"),
            Q("英语句子的第一个词的（　）要大写。", "首字母", "整个词", "最后一个字母", "中间字母"),
            Q("关于英语姓名，下列说法正确的是（　）。", "名在前，姓在后", "姓在前，名在后", "只有姓没有名", "只有名没有姓"),
        ]),
    ]),
    ("第三单元 We're Family", [
        ("第1课 核心词汇", "Today's words: family / parents / grandparents / brother / sister / cousin。学会介绍家庭成员。", build_vocab([
            ("family", "家庭"), ("parents", "父母"), ("grandparents", "祖父母/外祖父母"),
            ("brother", "哥哥或弟弟"), ("sister", "姐姐或妹妹"), ("cousin", "堂（表）兄弟姐妹"),
            ("uncle", "叔叔/舅舅"), ("aunt", "姑姑/阿姨"), ("son", "儿子"),
            ("daughter", "女儿"), ("grandma", "奶奶/外婆"), ("grandpa", "爷爷/外公"),
        ])),
        ("第2课 句型与对话", "Sentences: Who's this/that? / This is my ... / Are these your parents? 学会介绍全家福照片中的人物。", [
            Q("指着照片上的人问“这人是谁？”应该说（　）。", "Who's this?", "What's this person?", "Where is this?", "How is this person?"),
            Q("介绍照片中的爸爸说（　）。", "This is my father.", "These is my father.", "That am my father.", "It is father me."),
            Q("询问“这些是你的父母吗？”应说（　）。", "Are these your parents?", "Is these your parents?", "Are this your parent?", "Do these your parents?"),
            Q("肯定回答 Are these your parents? 说（　）。", "Yes, they are.", "Yes, these is.", "Yes, it is.", "Yes, they do."),
            Q("“My mother is a nurse.”的意思是（　）。", "我妈妈是护士。", "我妈妈喜欢护士。", "我妈妈在医院。", "护士是我妈妈的朋友。"),
            Q("“brother”可能指（　）。", "哥哥或弟弟", "姐姐或妹妹", "叔叔或舅舅", "儿子或女儿"),
            Q("“cousin”指的是（　）。", "堂（表）兄弟姐妹", "亲兄弟姐妹", "祖父母", "父母"),
            Q("“There are four people in my family.”的意思是（　）。", "我家有四口人。", "我家有四个房间。", "我家有四张照片。", "我家有四只猫。"),
            Q("询问“你家有几口人？”应说（　）。", "How many people are there in your family?", "How much people in your family?", "What people are in family?", "Who many people family?"),
            Q("“grandparents”包括（　）。", "爷爷、奶奶、外公、外婆", "爸爸和妈妈", "叔叔和阿姨", "儿子和女儿"),
            Q("介绍全家福时常用的开场语是（　）。", "This is a photo of my family.", "This is photo of I family.", "It's family photo to me.", "Here family is."),
            Q("“My father is tall and thin.”的意思是（　）。", "我爸爸又高又瘦。", "我爸爸喜欢高个子。", "我爸爸想变瘦。", "我爸爸很高但很强壮。"),
            Q("询问对方妈妈的职业，应说（　）。", "What does your mother do?", "Who is your mother do?", "Where is your mother do?", "How does your mother?"),
            Q("回答职业可以说（　）。", "She is a doctor.", "She do doctor.", "She is doctor do.", "Her is doctor."),
            Q("“family tree”的意思是（　）。", "家谱（家庭关系图）", "家里的树", "家中的花园", "家族的房子"),
            Q("“I love my family very much.”的意思是（　）。", "我非常爱我的家人。", "我家很大。", "我爱家人很少。", "我家人很多。"),
            Q("称呼“叔叔”用英语说（　）。", "uncle", "aunt", "cousin", "grandpa"),
            Q("“aunt”指（　）。", "姑姑/阿姨/舅妈等", "叔叔/舅舅", "爷爷", "孙子"),
            Q("“These are my grandparents.”的意思是（　）。", "这些是我的祖父母。", "这是我的祖父。", "这些是我的父母。", "那是我的祖母。"),
            Q("询问照片里“那个女孩是谁？”应说（　）。", "Who's that girl?", "What girl is that one?", "Where is that girl?", "How is the girl?"),
            Q("回答 Who's that girl? 可以说（　）。", "She is my sister.", "He is my sister.", "He is my brother.", "It is sister to me."),
            Q("下列表达家庭人数正确的句子是（　）。", "My family is a big one.", "My family are many.", "My family have big.", "My families is big."),
        ]),
        ("第3课 综合运用", "Describe your family members: appearance, jobs, hobbies. 综合运用本单元内容介绍家庭。", [
            Q("介绍妹妹的外貌特征可以说（　）。", "My sister has long hair.", "My sister is long hair.", "My sister hair long is.", "My sister with long hair has."),
            Q("“My parents are both teachers.”的意思是（　）。", "我父母都是老师。", "我父母有两个老师。", "我父母想当老师。", "我父母教两个老师。"),
            Q("下列关于英文中 brother 的说法正确的是（　）。", "不区分哥哥弟弟，都可称 brother", "只能指哥哥", "只能指弟弟", "指表哥"),
            Q("“elder brother”的意思是（　）。", "哥哥", "弟弟", "姐姐", "妹妹"),
            Q("“younger sister”的意思是（　）。", "妹妹", "姐姐", "弟弟", "哥哥"),
            Q("想表达“我有一个幸福的家”可以说（　）。", "I have a happy family.", "I am a happy family.", "I have happy a family.", "Me have a happy family."),
            Q("“His uncle is a policeman.”的意思是（　）。", "他的叔叔是警察。", "他的叔叔想当警察。", "警察是他的叔叔的朋友。", "他的叔叔喜欢警察。"),
            Q("英语中职业名词“driver”的意思是（　）。", "司机", "医生", "工人", "农民"),
            Q("“farmer”的意思是（　）。", "农民", "工人", "教师", "厨师"),
            Q("“My grandma likes cooking.”的意思是（　）。", "我奶奶喜欢做饭。", "我奶奶会煮饭卖。", "我奶奶喜欢书。", "我奶奶在做蛋糕。"),
            Q("介绍家人爱好，句型“...likes + 动名词”中动名词的意思是（　）。", "动词的 ing 形式", "动词原形", "动词过去式", "名词复数"),
            Q("“My cousin and I are in the same school.”的意思是（　）。", "我和表哥在同一所学校。", "我和表哥去同一方向。", "表哥想转学。", "我表哥不在这所学校。"),
            Q("询问“你爸爸多大了？”应说（　）。", "How old is your father?", "How old your father?", "What old is father?", "How your father old?"),
            Q("“She is kind to us.”中 kind 的意思是（　）。", "友善的", "种类", "一种", "善良的名词"),
            Q("全家福照片的英文说法是（　）。", "a photo of my family", "a family's photo to me", "my family a photo", "photo family of mine"),
            Q("“Who's the woman next to my father?”的意思是（　）。", "我爸爸旁边的那个女人是谁？", "我爸爸旁边的女人去哪了？", "我爸爸想见那个女人。", "那个女人认识我爸爸。"),
            Q("下列哪个词属于家庭成员称呼？（　）。", "nephew（侄子、外甥）", "driver", "autumn", "winter"),
            Q("“My mother does the cooking at home.”的意思是（　）。", "我妈妈在家做饭。", "我妈妈在家吃饭。", "我妈妈买书回家。", "我妈妈在家洗碗。"),
            Q("描述爸爸的职业是工人，应说（　）。", "My father is a worker.", "My father is worker.", "My father worker is.", "My father are a worker."),
            Q("“Thanks for your photo of your family.”的意思是（　）。", "谢谢你寄来的全家福照片。", "请把照片给我。", "你的照片很漂亮吗？", "我想看你家的照片。"),
            Q("英语中表达“爱我们的家人”可以说（　）。", "We should love our family members.", "We should loving family.", "Us love family member.", "Family love we should."),
            Q("下列关于英文称呼的说法正确的是（　）。", "grandpa 也可指外公", "grandpa 只指爷爷", "grandpa 指父母", "grandpa 指叔叔"),
        ]),
    ]),
    ("第四单元 My School", [
        ("第1课 核心词汇", "Today's words: classroom / library / playground / lab / canteen / gym。学会说出学校的各个场所。", build_vocab([
            ("classroom", "教室"), ("library", "图书馆"), ("playground", "操场"),
            ("lab", "实验室"), ("canteen", "食堂"), ("gym", "体育馆；健身房"),
            ("art room", "美术教室"), ("music room", "音乐教室"), ("teacher's office", "教师办公室"),
            ("desk", "书桌"), ("chair", "椅子"), ("building", "建筑物"),
        ])),
        ("第2课 句型与对话", "Sentences: Where is the library? / It's behind the classroom. / Is there a ...? 学会用方位词描述校园。", [
            Q("询问“图书馆在哪里？”应说（　）。", "Where is the library?", "What is the library?", "Who is in the library?", "When is the library?"),
            Q("“The playground is in front of the building.”的意思是（　）。", "操场在大楼前面。", "操场在大楼后面。", "操场在大楼里。", "操场在大楼上。"),
            Q("“behind”的意思是（　）。", "在……后面", "在……前面", "在……上面", "在……旁边"),
            Q("“Is there a gym in your school?”的肯定回答是（　）。", "Yes, there is.", "Yes, it is.", "Yes, there are.", "Yes, they are."),
            Q("询问“你们学校有图书馆吗？”应说（　）。", "Is there a library in your school?", "Are there a library in school?", "Have there a library?", "Does there a library?"),
            Q("“next to”的意思是（　）。", "紧挨着", "离得远", "在上面", "在下面"),
            Q("“The canteen is between the library and the lab.”中 between 表示（　）。", "在两者之间", "在三者中间任意位置", "在上方", "在对面"),
            Q("“We have lunch in the canteen.”的意思是（　）。", "我们在食堂吃午饭。", "我们在教室吃午饭。", "我们在食堂做午饭。", "我们在食堂买书。"),
            Q("去图书馆看书应说（　）。", "go to the library to read books", "go library read book", "go to library and read book to", "go the library reading"),
            Q("“There are many books in the library.”中 many 修饰（　）。", "可数名词复数", "不可数名词", "动词", "形容词"),
            Q("描述“教室里有 40 张桌椅”应说（　）。", "There are 40 desks and chairs in the classroom.", "There is 40 desks and chairs.", "It has 40 desk and chairs.", "There have 40 desks."),
            Q("“on the first floor”的意思是（　）。", "在一楼", "在顶层", "在楼外", "在楼上"),
            Q("“The teacher's office is on the second floor.”的意思是（　）。", "教师办公室在二楼。", "教师办公室有两个。", "办公室在二楼教师家。", "二楼是教师办公室吗？"),
            Q("“Our school is big and beautiful.”的意思是（　）。", "我们的学校又大又美。", "我们的学校大而旧。", "我们的学校想变大。", "我们的学校不美。"),
            Q("问“美术教室在哪里？”应说（　）。", "Where is the art room?", "What is the art room?", "Which is art room?", "When is the art room?"),
            Q("“in the middle of”的意思是（　）。", "在……中间", "在……前面", "在……末尾", "在……附近"),
            Q("指路“一直往前走”应说（　）。", "Go straight ahead.", "Go straightly ahead.", "Walk straight to ahead.", "Going straight on."),
            Q("“Turn left at the gate.”的意思是（　）。", "在大门口左转。", "大门在左边。", "从大门进去。", "左转去大门。"),
            Q("“The gym is opposite the canteen.”中 opposite 表示（　）。", "在……对面", "在……旁边", "在……上面", "穿过"),
            Q("询问“你们的学校大吗？”应说（　）。", "Is your school big?", "Does your school big?", "Are your school big?", "Do your school big?"),
            Q("“welcome to our school”的意思是（　）。", "欢迎来到我们学校", "欢迎回家", "学校很欢迎你", "欢迎来教我们"),
            Q("下列哪个场所用于做实验？（　）。", "lab", "canteen", "library", "playground"),
        ]),
        ("第3课 综合运用", "Describe your school: buildings, places, activities. 综合运用本单元内容介绍校园。", [
            Q("介绍学校布局时，通常先说（　）。", "学校总体情况", "每张桌子的位置", "老师的年龄", "课程的难度"),
            Q("“Our school has two teaching buildings.”的意思是（　）。", "我们学校有两栋教学楼。", "我们学校要建两栋楼。", "我们学校有两间教室。", "教学楼有两所学校。"),
            Q("表达“下课了，同学们去操场”应说（　）。", "After class, students go to the playground.", "After class, students go playground.", "Class over, students playground go.", "After class students to playground."),
            Q("“My classroom is clean and bright.”中 bright 的意思是（　）。", "明亮的", "聪明的", "轻的", "快的"),
            Q("“The library is a good place to read.”的意思是（　）。", "图书馆是读书的好地方。", "图书馆要读好书。", "好图书馆要读书。", "读书要去好图书馆。"),
            Q("“In the lab, we do experiments.”中 experiments 的意思是（　）。", "实验", "练习", "游戏", "聚会"),
            Q("询问“体育馆离教室远吗？”应说（　）。", "Is the gym far from the classroom?", "Does the gym far from classroom?", "Is gym far to classroom?", "Are gym far from classroom?"),
            Q("回答距离近可以说（　）。", "No, it's near.", "No, it's near from.", "No, it near.", "No, it is near to."),
            Q("“The school gate is always open at 7 a.m.”的意思是（　）。", "校门每天早上 7 点开。", "校门每天早上 7 点关。", "学校 7 点上课。", "校门每天 7 点锁。"),
            Q("“There is a big tree in front of the teaching building.”中 front 的意思是（　）。", "前面", "后面", "里面", "上面"),
            Q("下列关于 there be 句型的说法正确的是（　）。", "be 动词单复数与后面的名词一致", "一律用 is", "一律用 are", "与主语人称无关"),
            Q("“How many floors does the building have?”的正确答句是（　）。", "It has five floors.", "It is five floors.", "It has five floor.", "They are five floors."),
            Q("表达“欢迎来参观我们的学校”应说（　）。", "Welcome to visit our school.", "Welcome visit our school.", "Welcome to visiting school.", "Welcome our school visit."),
            Q("“The music room is on the third floor.”中 third 的意思是（　）。", "第三", "三分之一", "三次", "第三名"),
            Q("下列关于“食堂”的表达正确的是（　）。", "We eat meals in the canteen.", "We eat meals on the canteen.", "We eat meals at canteen of.", "We eat meals in canteens room."),
            Q("“Our school is like a garden.”运用的修辞是（　）。", "比喻", "拟人", "夸张", "反问"),
            Q("“The library closes at 5:30 p.m.”的意思是（　）。", "图书馆下午 5:30 关门。", "图书馆 5:30 开门。", "图书馆有 5:30 个座位。", "图书馆下午 5:30 闭馆吗？"),
            Q("描述位置“在拐角处”应说（　）。", "at the corner", "on the corner of in", "at corner the", "in the corner to"),
            Q("“Walk along this road and you'll see the gym.”的意思是（　）。", "沿这条路走，你会看到体育馆。", "这条路通向体育馆吗？", "体育馆在这条路尽头。", "沿路走不要去体育馆。"),
            Q("下列关于学校场所的说法正确的是（　）。", "canteen 是吃饭的地方", "canteen 是看书的地方", "canteen 是实验的地方", "canteen 是运动的地方"),
            Q("表达“操场很热闹”可以说（　）。", "The playground is lively.", "The playground is lively at.", "The playground lively is.", "The playground are lively."),
            Q("“Reading makes us smart.”中 smart 的意思是（　）。", "聪明的", "时髦的", "瘦的", "疼的"),
        ]),
    ]),
    ("第五单元 My Favourite Subject", [
        ("第1课 核心词汇", "Today's words: subject / maths / Chinese / history / geography / biology。学会说出各学科名称。", build_vocab([
            ("subject", "学科"), ("maths", "数学"), ("Chinese", "语文；中文"),
            ("history", "历史"), ("geography", "地理"), ("biology", "生物"),
            ("art", "美术"), ("music", "音乐"), ("physics", "物理"),
            ("chemistry", "化学"), ("politics", "道德与法治"), ("lesson", "课"),
        ])),
        ("第2课 句型与对话", "Sentences: What's your favourite subject? / Why do you like it? / Because it's interesting. 学会谈论喜欢的学科。", [
            Q("询问“你最喜欢的学科是什么？”应说（　）。", "What's your favourite subject?", "Who's your favourite subject?", "Which subject is you like?", "How is your favourite subject?"),
            Q("回答最喜爱的学科可以说（　）。", "My favourite subject is maths.", "Me favourite subject maths.", "I favourite subject is maths.", "My favourite subject maths is."),
            Q("询问“你为什么喜欢英语？”应说（　）。", "Why do you like English?", "What do you like English?", "How do you like English for?", "Where do you like English?"),
            Q("回答原因常用（　）引导的句子。", "Because", "But", "So", "Or"),
            Q("“Because it's interesting.”的意思是（　）。", "因为它很有趣。", "但是它很有趣。", "所以它有趣。", "它有趣吗？"),
            Q("“useful”的意思是（　）。", "有用的", "有趣的", "困难的", "无聊的"),
            Q("“I think maths is difficult.”中 difficult 的意思是（　）。", "困难的", "不同的", "聪明的", "新的"),
            Q("询问“你今天有什么课？”应说（　）。", "What classes do you have today?", "What classes you have today?", "Which classes have you today?", "How classes do you have?"),
            Q("回答课程可以说（　）。", "I have maths and Chinese.", "I am have maths and Chinese.", "I has maths and Chinese.", "Me have maths, Chinese."),
            Q("“history”的意思是（　）。", "历史", "故事", "他的故事", "医院"),
            Q("“geography”的意思是（　）。", "地理", "地质", "生物", "几何"),
            Q("“biology”的意思是（　）。", "生物", "身体", "博物馆", "图书馆"),
            Q("“When do you have art?”的意思是（　）。", "你们什么时候上美术课？", "你们有美术课吗？", "你们在美术课做什么？", "美术课在哪里上？"),
            Q("回答时间可以说（　）。", "We have art on Monday.", "We have art at Monday.", "We have art in Monday.", "We have art of Monday."),
            Q("“The music class begins at 10 o'clock.”中 begins 的意思是（　）。", "开始", "结束", "继续", "停止"),
            Q("表达“我最喜欢星期五因为下午没课”可以说（　）。", "I like Friday best because we have no classes in the afternoon.", "I like Friday best because have no classes afternoon.", "I best like Friday because afternoon no classes.", "I like Friday the best because we no have classes."),
            Q("询问“谁教你们语文？”应说（　）。", "Who teaches you Chinese?", "Who teach you Chinese?", "Who does teach you Chinese?", "Who teaching you Chinese?"),
            Q("回答 Who teaches you Chinese? 可以说（　）", "Mr Wang teaches us Chinese.", "Mr Wang teach us Chinese.", "Mr Wang teaching us Chinese.", "Mr Wang teach to us Chinese."),
            Q("“My favourite subject is science, because it's fun.”中 science 的意思是（　）。", "科学", "数学", "美术", "体育"),
            Q("“I'm good at geography.”中 be good at 的意思是（　）。", "擅长于", "喜欢于", "开始于", "到达"),
            Q("“We have a maths test tomorrow.”中 test 的意思是（　）。", "测验", "课本", "课文", "表格"),
            Q("下列学科中表示“体育”的是（　）。", "PE", "ME", "IT", "IQ"),
        ]),
        ("第3课 综合运用", "Talk about your school day and subjects. 综合运用本单元内容谈论课程表与喜好。", [
            Q("描述自己课程表时，通常先说（　）。", "一周的整体安排", "每一分钟的安排", "放学后的活动", "老师的姓名"),
            Q("“Monday, Tuesday, Wednesday”属于（　）。", "一周中的几天", "学科名称", "月份名称", "季节名称"),
            Q("“Thursday”的正确拼写是（　）。", "Thursday", "Thirsday", "Thusday", "Thursday的另一种拼法不存在"),
            Q("“Friday”的中文意思是（　）。", "星期五", "星期四", "星期六", "星期天"),
            Q("“What do you think of maths?”的意思是（　）。", "你认为数学怎么样？", "你学数学吗？", "你数学考了多少？", "你和数学谁好？"),
            Q("回答上述问题可以说（　）。", "It's interesting but a little difficult.", "Yes, I am.", "I likes it very much.", "It's at eight."),
            Q("“My timetable is full.”中 full 的意思是（　）。", "满的", "饱的", "空的", "完整的名词"),
            Q("表达“上午有四节课”应说（　）。", "We have four classes in the morning.", "We have four classes at morning.", "We have four class on morning.", "We has four classes in morning."),
            Q("“The last class ends at 4:50 p.m.”中 ends 的意思是（　）。", "结束", "开始", "结束的名词", "末端"),
            Q("询问“你最喜欢哪一天？”应说（　）。", "Which day do you like best?", "What day do you like the better?", "Which day you like best?", "How day do you like best?"),
            Q("回答 Which day do you like best? 可以说（　）", "I like Sunday best.", "I like best Sunday.", "Best Sunday I like.", "Sunday is like best."),
            Q("“because”后面接（　）。", "原因", "结果", "转折", "选择"),
            Q("下列关于 favourite 用法的说法正确的是（　）。", "favourite 前通常用形容词性物主代词，如 my favourite book", "favourite 后不加名词", "favourite 是动词", "favourite 与 like 完全不能替换"),
            Q("“Our English teacher is very funny.”中 funny 的意思是（　）。", "有趣的、滑稽的", "搞笑的错误", "滑稽的名词", "有趣地"),
            Q("表达“我喜欢地理因为它有用”应说（　）。", "I like geography because it's useful.", "I like geography because useful it is.", "I like geography because it useful is.", "I like geography because it is use."),
            Q("“art”作为学科指（　）。", "美术", "艺术理论", "文章", "运动员"),
            Q("询问“你妹妹喜欢什么学科？”应说（　）。", "What subject does your sister like?", "What subject do your sister like?", "What subject is your sister like?", "What subject your sister likes?"),
            Q("回答 What subject does your sister like? 可以说（　）", "She likes music.", "She like music.", "She liking music.", "Her likes music."),
            Q("“We have PE twice a week.”中 twice 的意思是（　）。", "两次", "两次半", "第二", "两倍地"),
            Q("下列关于学科的表达正确的是（　）。", "We study many subjects at school.", "We study many subject at school.", "We study much subjects at school.", "We study a subjects at school."),
            Q("“The class is over.”的意思是（　）。", "下课了", "课堂结束了名词", "课在上方", "课结束了吗？"),
            Q("表达“英语很有用”可以说（　）。", "English is very useful.", "English is very use.", "English very useful is.", "English are very useful."),
        ]),
    ]),
    ("第六单元 Fun Clubs", [
        ("第1课 核心词汇", "Today's words: club / join / guitar / chess / paint / dance。学会说出社团活动与爱好。", build_vocab([
            ("club", "社团"), ("join", "加入"), ("guitar", "吉他"),
            ("chess", "国际象棋"), ("paint", "绘画"), ("dance", "跳舞"),
            ("sing", "唱歌"), ("swim", "游泳"), ("draw", "画"),
            ("speak", "说（某种语言）"), ("drum", "鼓"), ("violin", "小提琴"),
        ])),
        ("第2课 句型与对话", "Sentences: What club do you want to join? / I want to join the music club. / Can you play the guitar? 学会谈论社团与能力。", [
            Q("询问“你想加入什么社团？”应说（　）。", "What club do you want to join?", "What club you want join?", "Which club do you want join to?", "How club do you want to join?"),
            Q("回答 What club do you want to join? 可以说（　）", "I want to join the music club.", "I want join music club.", "I wants to join the music club.", "I am want to join music club."),
            Q("询问“你会弹吉他吗？”应说（　）。", "Can you play the guitar?", "Do you can play the guitar?", "Are you play the guitar?", "Can you playing the guitar?"),
            Q("肯定回答 Can you swim? 说（　）。", "Yes, I can.", "Yes, I do.", "Yes, I am.", "Yes, I can swim it."),
            Q("否定回答 Can you play chess? 说（　）。", "No, I can't.", "No, I don't.", "No, I am not.", "No, I can't do it yes."),
            Q("“play the violin”中要加定冠词 the，因为（　）。", "乐器前常加 the", "专有名词前", "球类前", "都需加 the"),
            Q("“play basketball”中不加 the，因为（　）。", "球类运动前不加 the", "习惯性错误", "篮球是专有名词", "复数前不加"),
            Q("“join”的意思是（　）。", "加入", "喜悦", "玩耍", "工作"),
            Q("“She is good at dancing.”中 dancing 是（　）。", "动名词", "现在分词作谓语", "过去式", "名词复数"),
            Q("询问“你会做什么？”应说（　）。", "What can you do?", "What you can do?", "What do you can?", "How can you do?"),
            Q("回答 What can you do? 可以说（　）", "I can sing and dance.", "I can sing and dancing.", "I can to sing and dance.", "I can singing and dance."),
            Q("“the art club”的意思是（　）。", "美术社团", "艺术家人", "美术课", "画画的人"),
            Q("“join us”的意思是（　）。", "加入我们", "加入美国", "与我们一起玩", "向我们学习"),
            Q("“I can play the drums.”的意思是（　）。", "我会打鼓。", "我会玩鼓槌。", "我在打鼓吗？", "我喜欢鼓。"),
            Q("询问“他会说汉语吗？”应说（　）。", "Can he speak Chinese?", "Does he can speak Chinese?", "Can he speaks Chinese?", "Can he speaking Chinese?"),
            Q("“Can you help kids with swimming?”的意思是（　）。", "你能帮孩子们学游泳吗？", "你能和孩子游泳吗？", "你能在水里帮孩子吗？", "你想学游泳吗？"),
            Q("“be good with”的意思是（　）。", "善于与……相处", "擅长于（学科）", "对……好", "与……一样好"),
            Q("“musician”的意思是（　）。", "音乐家", "博物馆", "音乐课", "音乐"),
            Q("表达“我想要加入象棋社团”应说（　）。", "I want to join the chess club.", "I want join the chess club to.", "I want to joining chess club.", "I want to join chess club of."),
            Q("“Can you show me the way?”中 show 的意思是（　）。", "给……看；指引", "演出", "展示的名词", "节目"),
            Q("“Please call me at 555-3721.”中 at 表示（　）。", "（电话号码）拨……", "在（地点）", "在（时刻）", "朝（方向）"),
            Q("下列关于 can 的说法正确的是（　）。", "can 后接动词原形", "can 后接动名词", "can 后接 to do", "can 有人称变化"),
        ]),
        ("第3课 综合运用", "Write and talk about club activities. 综合运用本单元内容介绍社团招新。", [
            Q("社团招新海报通常不包括（　）。", "成员的银行账号", "社团名称", "活动时间", "联系方式"),
            Q("“Do you want to make new friends?”的意思是（　）。", "你想结交新朋友吗？", "你想做新朋友的事吗？", "你想认识新老师吗？", "你想交旧朋友吗？"),
            Q("“Then join the sports club!”的意思是（　）。", "那就加入体育社团吧！", "然后去体育馆。", "那么看看体育社团。", "接着参加运动会。"),
            Q("“We need help at the old people's home.”中 need 的意思是（　）。", "需要", "needle", "需要的东西", "必须地"),
            Q("“old people's home”指的是（　）。", "养老院", "老人家", "老房子", "老家"),
            Q("表达“你会唱歌或跳舞吗？”应说（　）。", "Can you sing or dance?", "Can you singing and dance?", "Can you singing or dance?", "Do you can sing or dance?"),
            Q("“or”在疑问句中的意思是（　）。", "或者", "和", "但是", "因此"),
            Q("“Come and show us!”中 us 是（　）。", "宾格代词（我们）", "主格代词", "形容词性物主代词", "名词性物主代词"),
            Q("询问“你们社团什么时候活动？”应说（　）。", "When does your club meet?", "When your club meet?", "When is your club meet?", "When do your club meets?"),
            Q("回答 When does your club meet? 可以说（　）", "We meet every Friday afternoon.", "We meet every Friday at afternoon.", "We meet on every Friday afternoon.", "We meets every Friday afternoon."),
            Q("“I'm in the reading club.”的意思是（　）。", "我在阅读社团。", "我读过那个社团。", "我想进读书社。", "我在读书。"),
            Q("表达“欢迎所有同学加入”应说（　）。", "All students are welcome to join.", "All students are welcome join.", "All students welcome to join to.", "All the students are welcome joining."),
            Q("“email me at tom@school.com”的意思是（　）。", "发电子邮件到 tom@school.com", "在 tom@school.com 找我", "给我的邮箱起名", "记住我的邮箱"),
            Q("“That sounds interesting.”中 sounds 的意思是（　）。", "听起来", "声音", "听起来（名词）", "发音"),
            Q("询问“你的爱好是什么？”应说（　）。", "What's your hobby?", "What your hobby is?", "Which is your hobby at?", "How is your hobby?"),
            Q("回答 What’s your hobby? 可以说（　）", "My hobby is playing chess.", "My hobby is play chess.", "My hobby plays chess.", "My hobby is to playing chess."),
            Q("“He can also play the piano.”中 also 的意思是（　）。", "也", "总是", "全部", "仍然"),
            Q("表达“我不会游泳但我想学”应说（　）。", "I can't swim, but I want to learn.", "I can't swim, but I want learning.", "I can't swim but I want to learn it to.", "I don't can swim, but I want learn."),
            Q("“practice”的意思是（　）。", "练习", "奖品", "祝贺", "表演"),
            Q("“We practice singing every day.”中 practice 后接（　）。", "动名词", "动词原形", "不定式", "过去式"),
            Q("下列关于 club 的说法正确的是（　）。", "club 是志趣相投者活动的团体", "club 只指俱乐部建筑", "club 指课程", "club 指球队场地"),
            Q("表达“来和我们做朋友吧”应说（　）。", "Come and make friends with us.", "Come make friends to us.", "Come and make friends to us.", "Come making friends with us."),
        ]),
    ]),
    ("第七单元 A Day in the Life", [
        ("第1课 核心词汇", "Today's words: wake up / get dressed / brush teeth / take a shower / homework。学会描述一天作息。", build_vocab([
            ("wake up", "醒来"), ("get dressed", "穿好衣服"), ("brush teeth", "刷牙"),
            ("take a shower", "洗澡"), ("have breakfast", "吃早饭"), ("go to school", "去上学"),
            ("have class", "上课"), ("do homework", "做作业"), ("go to bed", "上床睡觉"),
            ("usually", "通常"), ("always", "总是"), ("never", "从不"),
        ])),
        ("第2课 句型与对话", "Sentences: What time do you usually get up? / I usually get up at six thirty. 学会谈论作息时间。", [
            Q("询问“你通常几点起床？”应说（　）。", "What time do you usually get up?", "What time you usually get up?", "When do you usually get up to?", "How time do you get up?"),
            Q("回答“六点半起床”应说（　）。", "I usually get up at six thirty.", "I usually get up on six thirty.", "I usually get up in six thirty.", "I usually get up six thirty."),
            Q("“half past six”的意思是（　）。", "六点半", "六点十五", "六点四十五", "七点半"),
            Q("“quarter to seven”的意思是（　）。", "六点四十五", "七点十五", "七点四十五", "六点一刻"),
            Q("“take a shower”的意思是（　）。", "洗澡", "散步", "淋浴器", "刮风"),
            Q("“have breakfast”的意思是（　）。", "吃早饭", "做饭", "买早饭", "休息一下"),
            Q("询问“你几点上学？”应说（　）。", "What time do you go to school?", "What time you go to school?", "When you go to school?", "What time are you go to school?"),
            Q("“do homework”的意思是（　）。", "做作业", "家务", "家庭作业本", "在家工作"),
            Q("“go to bed”的意思是（　）。", "上床睡觉", "去床边", "整理床铺", "睡觉的名词"),
            Q("“always”表示（　）。", "总是（频率 100%）", "通常", "经常", "从不"),
            Q("“usually”表示（　）。", "通常", "总是", "有时", "从不"),
            Q("“never”表示（　）。", "从不", "从不（肯定）", " ever 的否定", "曾经"),
            Q("“He usually goes to bed at ten.”中 goes 用第三人称单数因为（　）。", "主语是第三人称单数", "时间状语决定", "usually 决定", "习惯用法无规则"),
            Q("询问“你爸爸几点上班？”应说（　）。", "What time does your father go to work?", "What time does your father goes to work?", "What time do your father go to work?", "What time is your father go to work?"),
            Q("“in the morning”的意思是（　）。", "在早上", "在明天早上", "早上好", "早晨见面"),
            Q("“at noon”的意思是（　）。", "在中午", "在夜里", "在下午", "在早上"),
            Q("“in the evening”的意思是（　）。", "在晚上", "在傍晚问好", "每晚", "在夜里睡觉"),
            Q("“We have lunch at school.”中 at school 表示（　）。", "在学校（地点）", "在学校（时间）", "上学（动作）", "放学"),
            Q("表达“我总是七点刷牙”应说（　）。", "I always brush my teeth at seven.", "I always brush my tooth at seven.", "I always brush teeth at seven.", "I always brushing my teeth at seven."),
            Q("“What a funny time to eat breakfast!”的意思是（　）。", "吃早饭的时间真有趣！", "早饭真好吃！", "早饭时间到了！", "早餐很搞笑吗？"),
            Q("“late”的反义词是（　）。", "early", "fast", "slow", "quick"),
            Q("“on weekdays”的意思是（　）。", "在工作日", "在周末", "在假期", "每天"),
        ]),
        ("第3课 综合运用", "Describe your daily routine. 综合运用本单元内容写一日作息。", [
            Q("描述一天作息通常按（　）顺序。", "时间", "地点", "重要性", "因果"),
            Q("“My day starts early.”中 starts 的意思是（　）。", "开始", "学习", "出发的名词", "启明星"),
            Q("“in the afternoon”后面常搭配的动作是（　）。", "have classes", "go to bed", "have breakfast", "get dressed"),
            Q("“After dinner, I do my homework.”的意思是（　）。", "晚饭后我做作业。", "晚饭前我做作业。", "我晚饭吃作业。", "我带作业去吃饭。"),
            Q("询问“你周末通常做什么？”应说（　）。", "What do you usually do on weekends?", "What do you usually do at weekend of?", "What you usually do weekends?", "How do you usually do on weekends?"),
            Q("回答 What do you usually do on weekends? 可以说（　）", "I usually play football with my friends.", "I usually playing football with friends.", "I usually plays football with my friends.", "I usually to play football with friends."),
            Q("“She gets up early every day.”中 every day 表示（　）。", "每天（频度）", "每一天的名词", "每天地", "日常的形容词"),
            Q("“daily routine”的意思是（　）。", "日常作息", "日常路线", "日常规则", "日常事务"),
            Q("表达“他上学从不迟到”应说（　）。", "He is never late for school.", "He never is late for school.", "He is late never for school.", "He never late for school is."),
            Q("“be late for”的意思是（　）。", "做……迟到", "为……晚点", "迟到者", "迟到地"),
            Q("“My mother cooks breakfast for us.”中 cooks 的意思是（　）。", "做饭（动词）", "厨师（名词）", "炊具", "烹饪术"),
            Q("“I go to school by bike.”的意思是（　）。", "我骑车上学。", "我买自行车上学。", "我在学校骑车。", "我把自行车放学校。"),
            Q("“on foot”的意思是（　）。", "步行", "用脚踢", "站着", "在脚下"),
            Q("表达“放学后我踢半小时足球”应说（　）。", "I play football for half an hour after school.", "I play football half an hour after school.", "I play football for half a hour after the school.", "I play the football for half an hour after school."),
            Q("“It's time to go to bed.”的意思是（　）。", "该睡觉了", "该起床了", "是睡觉的时间名词", "睡觉时间很长"),
            Q("“It's time to + 动词原形”表示（　）。", "该做某事了", "做某事的时间名词", "时间到了", "是时间"),
            Q("表达“我的作息很规律”可以说（　）。", "My daily routine is regular.", "My daily routine is regular to.", "My daily routine regular is.", "My daily is regular routine."),
            Q("“regular”的意思是（　）。", "有规律的", "规则的名词", "经常地", "统治者"),
            Q("“I never stay up late.”中 stay up 的意思是（　）。", "熬夜", "呆在上面", "站起来", "留下来"),
            Q("“healthy”的意思是（　）。", "健康的", "卫生的名词", "健康地", "医院"),
            Q("下列作息习惯最健康的是（　）。", "早睡早起，按时吃饭", "熬夜到凌晨", "不吃早饭", "睡到中午"),
            Q("表达“我通常在晚饭后散步”应说（　）。", "I usually take a walk after dinner.", "I usually take walk after the dinner.", "I usually take a walk after the dinner.", "I usually take a walk in dinner."),
        ]),
    ]),
    ("第八单元 Happy Birthday", [
        ("第1课 核心词汇", "Today's words: January ~ December 月份与节日。学会说出月份与日期。", build_vocab([
            ("January", "一月"), ("February", "二月"), ("March", "三月"),
            ("April", "四月"), ("May", "五月"), ("June", "六月"),
            ("July", "七月"), ("August", "八月"), ("September", "九月"),
            ("October", "十月"), ("November", "十一月"), ("December", "十二月"),
        ])),
        ("第2课 句型与对话", "Sentences: When is your birthday? / My birthday is on May 4th. 学会谈论生日与日期。", [
            Q("询问“你的生日是什么时候？”应说（　）。", "When is your birthday?", "What is your birthday?", "Where is your birthday?", "Who is your birthday?"),
            Q("回答“我的生日在五月四日”应说（　）。", "My birthday is on May 4th.", "My birthday is at May 4th.", "My birthday is in May 4th.", "My birthday is May 4th on."),
            Q("“January”的缩写形式是（　）。", "Jan.", "Ja.", "Jany.", "Jn."),
            Q("“September”的缩写形式是（　）。", "Sept.", "Sep t.", "Spt.", "St."),
            Q("“May”的特点是（　）。", "没有缩写形式", "缩写为 Ma.", "缩写为 May.", "缩写为 My."),
            Q("表达日期“12 月 25 日”应说（　）。", "December 25th", "December 25th of", "25 Decemberth", "the December 25"),
            Q("“first”是序数词，表示（　）。", "第一", "一", "第一次地", "单个"),
            Q("“second”的意思是（　）。", "第二", "秒", "秒钟", "片刻"),
            Q("“third”的意思是（　）。", "第三", "三", "三倍", "三分之一"),
            Q("“fourth”的正确拼写是（　）。", "fourth", "forth", "fourt", "fourthly"),
            Q("“twelfth”的意思是（　）。", "第十二", "二十", "二等", "十二倍"),
            Q("“How old are you?”的回答可以是（　）。", "I'm twelve years old.", "I'm twelfth years old.", "I have twelve years old.", "I'm twelve year old."),
            Q("“Happy birthday to you!”的应答是（　）。", "Thank you!", "You're welcome!", "Happy birthday, too!", "The same to you, too."),
            Q("“birthday party”的意思是（　）。", "生日聚会", "生日礼物", "生日蛋糕", "生日卡片"),
            Q("表达“我们为她开个生日聚会吧”应说（　）。", "Let's have a birthday party for her.", "Let's have birthday party for she.", "Let us to have a birthday party for her.", "Let's having a birthday party for her."),
            Q("“How about a surprise party?”的意思是（　）。", "来个惊喜聚会怎么样？", "惊喜聚会在哪里？", "你知道惊喜聚会吗？", "你想要个惊喜吗？"),
            Q("“That sounds great!”的意思是（　）。", "听起来太棒了！", "那真棒吗？", "听起来很长的。", "声音很好听！"),
            Q("询问“你想要什么生日礼物？”应说（　）。", "What would you like for your birthday?", "What you would like for birthday?", "What do you like your birthday for?", "Which would you like birthday?"),
            Q("回答 What would you like for your birthday? 可以说（　）", "I'd like a new bike.", "I'd like a new bike to.", "I'd like to a new bike.", "I like a new bike."),
            Q("“make a wish”的意思是（　）。", "许愿", "许愿池", "希望做", "愿望"),
            Q("“blow out the candles”的意思是（　）。", "吹灭蜡烛", "点蜡烛", "买蜡烛", "做蛋糕"),
            Q("“in May”与“on May 4th”的区别是（　）。", "in 后接月份，on 后接具体某一天", "意思相同", "in 用于日期，on 用于月份", "没有区别"),
        ]),
        ("第3课 综合运用", "Plan a birthday party and talk about dates. 综合运用本单元内容策划生日聚会。", [
            Q("生日聚会的邀请卡通常不包括（　）。", "客人的家庭收入", "时间", "地点", "联系方式"),
            Q("“You are invited to my birthday party.”的意思是（　）。", "邀请你参加我的生日聚会。", "我被邀请参加聚会。", "我的聚会有邀请卡。", "你的聚会邀请我了吗？"),
            Q("表达“聚会在我家举行”应说（　）。", "The party is at my home.", "The party is on my home.", "The party at my home is.", "The party is in my home of."),
            Q("“It starts at 6 p.m. on Saturday.”的意思是（　）。", "周六下午 6 点开始。", "周六下午 6 点结束。", "周六有 6 个人来。", "开始时间未知。"),
            Q("“See you at the party!”的意思是（　）。", "聚会见！", "在聚会见面吗？", "聚会结束了。", "你去看聚会吗？"),
            Q("询问“你的生日聚会办得怎么样？”应说（　）。", "How was your birthday party?", "How is your birthday party was?", "What was your birthday party?", "Where was your birthday party?"),
            Q("回答“非常有趣”可以说（　）。", "It was great fun.", "It was great fun to.", "It is great fun, too.", "It great fun was."),
            Q("“Thank you for coming.”的意思是（　）。", "谢谢你的光临。", "谢谢你要来。", "谢谢你来了吗？", "感谢光临的礼物。"),
            Q("表达“收到你的礼物我很开心”应说（　）。", "I'm so happy to get your present.", "I'm so happy get your present.", "I'm so happy to getting your present.", "I so happy to get your present."),
            Q("“present”在“a birthday present”中的意思是（　）。", "礼物", "现在", "出席", "呈现"),
            Q("“This is the best gift ever!”的意思是（　）。", "这是我收到过的最好的礼物！", "这是最好的礼物店！", "这礼物最贵！", "这是我第一次收礼物！"),
            Q("“year after year”的意思是（　）。", "年复一年", "很多年前", "一年间", "多年以后"),
            Q("表达“下个月是我的生日”应说（　）。", "My birthday is next month.", "My birthday is on next month.", "My birthday is in next month.", "My birthday next month is."),
            Q("“calendar”的意思是（　）。", "日历", "照相机", "蜡烛", "卡片"),
            Q("“August is the eighth month of the year.”中 eighth 的意思是（　）。", "第八", "八个", "第八十", "八倍"),
            Q("下列月份中属于第二季度（4~6 月）的是（　）。", "May", "March", "July", "October"),
            Q("“What's the date today?”的意思是（　）。", "今天是几月几号？", "今天星期几？", "今天天气如何？", "今天几号你的生日？"),
            Q("回答日期可以说（　）。", "It's October 1st.", "It's in October 1st.", "It's October one.", "It's first October of."),
            Q("“What day is it today?”的意思是（　）。", "今天星期几？", "今天是几号？", "今天什么节日？", "今天你怎么样？"),
            Q("回答星期可以说（　）。", "It's Monday.", "It's Monday a today.", "It's the Monday.", "Today is at Monday."),
            Q("表达“祝你生日快乐、学习进步”应说（　）。", "Happy birthday and good luck with your study.", "Happy birthday and good luck with your study to.", "Happy birthday and good luck on your study.", "Happy birthday and good luck for study."),
            Q("“age”的意思是（　）。", "年龄", "时代（另义）", " aged 的原形", "老化"),
        ]),
    ]),
    ("第九单元 复习与检测", [
        ("第1课 Revision 1 综合复习一", "Review Starter and Units 1-4: greetings, family, school, subjects.", [
            Q("与朋友见面打招呼可以说（　）。", "Hi! How are you?", "Hi! How are you to?", "Hi! Who are you?", "Hi! What are you?"),
            Q("“My father is a doctor.”中 doctor 的意思是（　）。", "医生", "司机", "老师", "护士"),
            Q("“The library is behind the classroom building.”中 behind 表示（　）。", "在……后面", "在……前面", "在……旁边", "在……对面"),
            Q("询问学科“你最喜欢什么课？”应说（　）。", "What's your favourite subject?", "What your favourite subject?", "Which your favourite subject?", "How is your favourite subject?"),
            Q("“My mother's sister is my（　）。”,", "aunt", "uncle", "cousin", "grandma"),
            Q("“There are some books on the desk.”中 some 修饰（　）。", "可数或不可数名词", "只可数名词", "只不可数名词", "动词"),
            Q("“I can play the piano.”中 the 不能省略，因为（　）。", "乐器名词前加 the", "钢琴是唯一的", "习惯错误", "单数前必须加"),
            Q("“We're Family!”是照片题目的常见说法，意思是（　）。", "我们是一家人！", "我们是朋友！", "我们同一班！", "我们同岁！"),
            Q("回答 What's your last name? 说（　）。", "My last name is Smith.", "My last name is Smith to.", "My last name are Smith.", "Me last name is Smith."),
            Q("“because”与“so”在英语句子中（　）。", "不能同时使用", "必须同时使用", "可以同时使用", "没有区别"),
            Q("“She goes to school at seven.”的否定句是（　）。", "She doesn't go to school at seven.", "She doesn't goes to school at seven.", "She not goes to school at seven.", "She doesn't go to school on seven."),
            Q("“family”统指家庭成员时谓语动词用（　）。", "单数", "复数", "单复均可但意思不同", "无谓语"),
            Q("“The canteen is between the library and the gym.”中 between 后面接（　）。", "and 连接的两个对象", "to 连接的两个对象", "or 连接的两个对象", "单一个对象"),
            Q("“How many”用来提问（　）。", "可数名词的数量", "不可数名词的数量", "价格", "年龄"),
            Q("“How much”可以用来提问（　）。", "价格或不可数名词的量", "可数名词的个数", "年龄", "日期"),
            Q("“My favourite subject is art because it's relaxing.”中 relaxing 的意思是（　）。", "令人放松的", "放松（动作）", "休息", "懒散的"),
            Q("“Where is the school gate?”的正确答句是（　）。", "It's in front of the teaching building.", "It's front of the teaching building.", "It's in front the teaching building.", "It in front of the teaching building."),
            Q("“Nice to meet you.”用于（　）。", "初次见面", "再次见面", "告别", "道谢"),
            Q("“See you later.”用于（　）。", "告别", "见面", "道谢", "道歉"),
            Q("“These are my parents.”的疑问句是（　）。", "Are these your parents?", "Is these your parents?", "Are these your parent?", "Do these your parents?"),
            Q("“What time does the class begin?”的意思是（　）。", "课几点开始？", "课几点结束？", "课在哪里上？", "课有多长？"),
            Q("“My school day starts at 8 a.m.”中 a.m. 表示（　）。", "上午", "下午", "晚上", "中午"),
            Q("“p.m.”表示（　）。", "下午", "上午", "中午", "凌晨"),
        ]),
        ("第2课 Revision 2 综合复习二", "Review Units 5-8: clubs, daily routine, dates, birthdays.", [
            Q("“I want to join the chess club.”中 want 后面接（　）。", "to do 不定式", "doing", "done", "动词原形"),
            Q("“He can swim well.”的疑问句是（　）。", "Can he swim well?", "Does he can swim well?", "Can he swims well?", "Is he can swim well?"),
            Q("“get dressed”的意思是（　）。", "穿好衣服", "脱衣服", "买衣服", "洗衣服"),
            Q("“I usually get up at 6:30 in the morning.”中 usually 的位置（　）。", "在实义动词之前", "在实义动词之后", "在句末", "在句首"),
            Q("“always / usually / often / never”是（　）。", "频度副词", "时间副词", "地点副词", "方式副词"),
            Q("“half past nine”等于（　）。", "9:30", "9:15", "9:45", "8:30"),
            Q("“quarter past eight”等于（　）。", "8:15", "8:30", "8:45", "7:45"),
            Q("“quarter to ten”等于（　）。", "9:45", "10:15", "10:45", "9:15"),
            Q("“My birthday is in June.”中用 in 因为（　）。", "月份前用 in", "月份前用 on", "月份前用 at", "没有规律"),
            Q("“on June 1st”中用 on 因为（　）。", "具体某一天前用 on", "具体某一天前用 in", "具体某一天前用 at", "习惯用 for"),
            Q("“What do you usually do on weekends?”中 weekends 前（　）。", "用 on", "用 in", "用 at", "不加介词"),
            Q("“She is good at singing.”的同义句是（　）。", "She does well in singing.", "She is good for singing.", "She is good with singing.", "She is well in singing."),
            Q("“come on”在口语中可表示（　）。", "加油；快点", "来吧（离开）", "过来", "开始"),
            Q("“That sounds good.”中 sound 是（　）。", "系动词", "实义动词", "助动词", "情态动词"),
            Q("“How old is your best friend?”的正确答句是（　）。", "He is thirteen.", "He is thirteenth.", "He has thirteen.", "He thirteen."),
            Q("“We have a school trip in October.”中 school trip 的意思是（　）。", "学校旅行（郊游）", "学校旅行团", "学校的旅店", "校园巡视"),
            Q("“Thank you for your help.”中 for 表示（　）。", "原因", "目的（为了得到帮助而谢）", "所属", "方向"),
            Q("“Let's make a plan for the party.”中 make a plan 的意思是（　）。", "制定计划", "做平面图", "制定法律", "做决定"),
            Q("“What club does she want to join?”的正确答句是（　）。", "She wants to join the art club.", "She want to join the art club.", "She wants join the art club.", "She wanting to join the art club."),
            Q("“I go to bed at ten every day.”中 at ten 表示（　）。", "时间点", "时间段", "年龄", "地点"),
            Q("“It's time for class.”与“（　）”意思相同。", "It's time to have class.", "It's time to class.", "It's time having class.", "It's time for have class."),
            Q("“Wish you a happy birthday!”的同义句是（　）。", "Happy birthday to you!", "You have a happy birthday to!", "Wish you happy birthday you!", "Happy you a birthday!"),
        ]),
    ]),
]

if __name__ == "__main__":
    run(r"content/middle/pep/grade1/volume1/english", "英语上册", UNITS)
