# -*- coding: utf-8 -*-
"""人教版（2024 新教材）初中一年级下册英语全部单元交互自测题生成脚本。"""
import random

from _quizlib import S, S2, M, run


RNG = random.Random(20261202)


def _others(correct, pool, n=3):
    xs = [x for x in pool if x != correct]
    RNG.shuffle(xs)
    return xs[:n]


def en2cn(en, cn, pool_cn):
    return ("s", "「%s」的意思是（　）。" % en, [cn] + _others(cn, pool_cn), ["A"])


def cn2en(cn, en, pool_en):
    return ("s", "「%s」用英语说是（　）。" % cn, [en] + _others(en, pool_en), ["A"])


def first_letter(en, pool_letters):
    answer = en[0].upper()
    return ("s", "单词或短语「%s」的第一个字母是（　）。" % en,
            [answer] + _others(answer, pool_letters), ["A"])


def letter_case(letter):
    up, low = letter.upper(), letter.lower()
    return ("s", "大写字母「%s」的小写形式是（　）。" % up,
            [low, up, chr((ord(low) - 97 + 1) % 26 + 97),
             chr((ord(low) - 97 + 2) % 26 + 97)], ["A"])


def build_vocab(words, want=22):
    pool_cn = [cn for _, cn in words]
    pool_en = [en for en, _ in words]
    letters = list("ABCDEFGHIJKLMNOPQRSTW")
    questions = []
    for en, cn in words:
        questions.append(en2cn(en, cn, pool_cn))
        questions.append(cn2en(cn, en, pool_en))
        if len(en) >= 3:
            questions.append(first_letter(en, letters))
    for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
        questions.append(letter_case(letter))
    seen, result = set(), []
    for question in questions:
        if question[1] in seen:
            continue
        seen.add(question[1])
        result.append(question)
    RNG.shuffle(result)
    return result[:want]


def Q(stem, ans, *wrong):
    return S(stem, ans, [str(item) for item in wrong])


UNITS = [
    ("第一单元 Animal Friends", [
        ("第1课 核心词汇", "Today's words: panda / lion / elephant / giraffe / dangerous / friendly。学会说出动物名称。", build_vocab([
            ("panda", "熊猫"), ("lion", "狮子"), ("elephant", "大象"),
            ("giraffe", "长颈鹿"), ("tiger", "老虎"), ("monkey", "猴子"),
            ("dangerous", "危险的"), ("friendly", "友好的"), ("clever", "聪明的"),
            ("beautiful", "美丽的"), ("scary", "吓人的"), ("cute", "可爱的"),
        ])),
        ("第2课 句型与对话", "Sentences: What's your favourite animal? / Why do you like pandas? 学会谈论喜欢的动物并说明理由。", [
            Q("询问“你最喜欢的动物是什么？”应说（　）。", "What's your favourite animal?", "Who's your favourite animal?", "Which animal is you like?", "How is your favourite animal?"),
            Q("回答 What’s your favourite animal? 可以说（　）", "My favourite animal is the panda.", "My favourite animal panda is.", "I favourite animal is panda.", "Me favourite animal is panda."),
            Q("询问“你为什么喜欢长颈鹿？”应说（　）。", "Why do you like giraffes?", "What do you like giraffes?", "How do you like giraffes?", "Where do you like giraffes?"),
            Q("回答原因可以说（　）。", "Because they are very beautiful.", "Because they is very beautiful.", "Because they are very beauty.", "Because they has very beautiful."),
            Q("“elephant”的意思是（　）。", "大象", "蚂蚁", "老虎", "袋鼠"),
            Q("“Pandas are shy animals.”中 shy 的意思是（　）。", "害羞的", "高大的", "危险的", "聪明的"),
            Q("“The lion is scary.”中 scary 的意思是（　）。", "吓人的", "友好的", "可爱的", "安静的"),
            Q("描述“大象很大”应说（　）。", "The elephant is very big.", "The elephant is very big to.", "The elephant very big is.", "The elephant are very big."),
            Q("询问“它来自哪里？”应说（　）。", "Where is it from?", "Where it is from?", "Where is it come from?", "Where does it from?"),
            Q("回答 Where is it from? 可以说（　）", "It's from China.", "It from China.", "It is come from China.", "It comes from to China."),
            Q("“dolphin”的意思是（　）。", "海豚", "海豹", "鲨鱼", "鲸鱼"),
            Q("“penguin”的意思是（　）。", "企鹅", "鹦鹉", "海豚", "鸭子"),
            Q("表达“我不喜欢老虎因为它们吓人”应说（　）。", "I don't like tigers because they are scary.", "I don't like tigers because they scary are.", "I no like tigers because scary.", "I don't likes tigers because they are scary."),
            Q("“save the animals”的意思是（　）。", "拯救动物", "节省动物", "喂食动物", "参观动物"),
            Q("“They are in great danger.”中 in danger 的意思是（　）。", "处于危险中", "很危险的人", "危险的地方", "危险的动作"),
            Q("“friendly”的名词形式是（　）。", "friend", "friendship", "friendly 名词无", "friends"),
            Q("描述“猴子很聪明”应说（　）。", "Monkeys are clever.", "Monkeys is clever.", "Monkey are clever.", "Monkeys clever are."),
            Q("询问“动物园里有什么动物？”应说（　）。", "What animals are there in the zoo?", "What animals there are in the zoo?", "What animals is there in the zoo?", "Which animals there in zoo?"),
            Q("回答 What animals are there in the zoo? 可以说（　）", "There are lions, tigers and pandas.", "There is lions, tigers and pandas.", "They are lions, tigers and pandas.", "There have lions, tigers and pandas."),
            Q("“kill”的意思是（　）。", "杀害", "保持", "喂食", "抚摸"),
            Q("表达“我们应保护动物”应说（　）。", "We should protect animals.", "We should protect animal.", "We should protecting animals.", "We should to protect animals."),
            Q("“protect”的意思是（　）。", "保护", "项目", "产品", "证明"),
        ]),
        ("第3课 综合运用", "Describe animals and talk about protecting them. 综合运用本单元内容介绍动物朋友。", [
            Q("介绍熊猫可以说（　）。", "Pandas are black and white.", "Pandas is black and white.", "Panda are black and white.", "Pandas are black and white to."),
            Q("“Giraffes have long necks.”中 neck 的意思是（　）。", "脖子", "腿", "尾巴", "耳朵"),
            Q("“Elephants have long trunks.”中 trunk 的意思是（　）。", "象鼻", "树干（另一义）", "行李箱（另一义）", "尾巴"),
            Q("表达“狮子是百兽之王”应说（　）。", "The lion is the king of the forest.", "The lion is king of the forest to.", "The lion are the king of forest.", "Lion is the king of the forest."),
            Q("“koala”的意思是（　）。", "考拉", "袋鼠", "骆驼", "斑马"),
            Q("“kangaroo”的意思是（　）。", "袋鼠", "考拉", "狐狸", "狼"),
            Q("描述“狗对人友好”应说（　）。", "Dogs are friendly to people.", "Dogs are friendly for people.", "Dogs are friend to people.", "Dogs are friendly with people."),
            Q("“Which animal do you like best?”的同义句是（　）。", "What's your favourite animal?", "Which animal do you like?（少 best）", "What animal do you like best?（同义）", "How do you like animals?"),
            Q("“fox”的意思是（　）。", "狐狸", "狼", "熊", "鹿"),
            Q("“wolf”的复数形式是（　）。", "wolves", "wolfs", "wolfes", "wolf"),
            Q("表达“它们白天睡觉”应说（　）。", "They sleep during the day.", "They sleep at the day.", "They sleep on the day.", "They are sleep during the day."),
            Q("“during the day”的反义短语是（　）。", "at night", "in the morning", "all day", "every day"),
            Q("“People cut down trees, so animals are losing their homes.”中 lose 的意思是（　）。", "失去", "输掉比赛（另一义）", "丢失（另一义）", "松开"),
            Q("表达“请别喂动物”应说（　）。", "Please don't feed the animals.", "Please don't feed to the animals.", "Please not feed the animals.", "Please don't feeding the animals."),
            Q("“feed”的意思是（　）。", "喂养", "脚（另一义）", "感觉", "座位"),
            Q("“A panda looks like a bear.”中 look like 的意思是（　）。", "看起来像", "喜欢看", "看着像要", "查找"),
            Q("“The zoo has over 100 kinds of animals.”中 kinds 的意思是（　）。", "种类", "善良的（另一义）", "种类（单数）", "孩子们"),
            Q("表达“我最喜欢的动物是海豚，因为它们聪明”应说（　）。", "My favourite animals are dolphins because they are smart.", "My favourite animal is dolphin because they is smart.", "My favourite animals are dolphin because it is smart.", "My favourite animals is dolphins because they are smart."),
            Q("“bamboo”的意思是（　）。", "竹子", "香蕉", "树叶", "草地"),
            Q("描述“熊猫吃竹子”应说（　）。", "Pandas eat bamboo.", "Pandas eats bamboo.", "Pandas eat bamboos.", "Panda eats bamboo."),
            Q("“There are fewer and fewer wild animals.”中 fewer and fewer 的意思是（　）。", "越来越少", "越来越多", "更少的", "最少的"),
            Q("表达“动物是我们的朋友”应说（　）。", "Animals are our friends.", "Animals is our friends.", "Animals are we friends.", "Animal are our friends."),
        ]),
    ]),
    ("第二单元 No Rules, No Order", [
        ("第1课 核心词汇", "Today's words: rule / hallway / uniform / arrive / fight / quiet。学会谈论校规班规。", build_vocab([
            ("rule", "规则"), ("hallway", "走廊"), ("uniform", "校服"),
            ("arrive", "到达"), ("fight", "打架"), ("quiet", "安静的"),
            ("strict", "严格的"), ("outside", "在外面"), ("practice", "练习"),
            ("dining hall", "食堂"), ("listen to", "听"), ("sorry", "抱歉的"),
        ])),
        ("第2课 句型与对话", "Sentences: Don't run in the hallways. / What are the rules? / We have to wear uniforms. 学会用祈使句谈论规则。", [
            Q("“Don't run in the hallways.”的意思是（　）。", "不要在走廊里跑。", "在走廊里跑步。", "走廊里能跑吗？", "别在走廊里走。"),
            Q("否定祈使句的构成是（　）。", "Don't + 动词原形", "Don't + 动名词", "Not + 动词原形", "Don't + 过去式"),
            Q("询问“有什么规定？”应说（　）。", "What are the rules?", "What is the rules?", "Which are the rules?", "How are the rules?"),
            Q("表达“我们必须穿校服”应说（　）。", "We have to wear uniforms.", "We have to wearing uniforms.", "We has to wear uniforms.", "We have wear uniforms."),
            Q("“have to”的意思是（　）。", "不得不；必须", "有（某种）", "不得不的过去式", "必须地"),
            Q("“We can't arrive late for class.”中 arrive late 的意思是（　）。", "迟到", "晚到的", "迟到的名词", "到达"),
            Q("“be late for”与“（　）”意思相近。", "arrive late for", "get to late", "come late of", "late to be"),
            Q("表达“不许打架”应说（　）。", "Don't fight.", "Don't fighting.", "Not fight.", "No fighting!（也常见，但校牌常用 Don't fight）"),
            Q("“Keep quiet in the library.”的意思是（　）。", "在图书馆保持安静。", "在图书馆很快。", "图书馆很安静。", "在图书馆安睡。"),
            Q("“listen to music”的意思是（　）。", "听音乐", "听音乐课", "听音乐的录音", "音乐"),
            Q("表达“上课不能听音乐”应说（　）。", "We can't listen to music in class.", "We can't listen music in class.", "We can't listening to music in class.", "We can't to listen to music in class."),
            Q("“Do we have to wear a uniform at school?”的肯定回答是（　）。", "Yes, we do.", "Yes, we have.", "Yes, we are.", "Yes, we can."),
            Q("“My parents are strict with me.”中 be strict with 的意思是（　）。", "对……要求严格", "对……严格地", "严格的", "严守的"),
            Q("表达“走廊里禁止喧哗”应说（　）。", "Don't talk loudly in the hallways.", "Don't talk loud in the hallways.", "Don't loudly talk in the hallways.", "Don't to talk loudly in hallways."),
            Q("“Don't eat in class.”的肯定说法是（　）。", "You can eat in the dining hall.", "You can eat at the dining hall.", "You can eat on the dining hall.", "You can eat in dining hall."),
            Q("“on school nights”的意思是（　）。", "在上学日的晚上", "在学校夜里", "在校晚上", "夜校"),
            Q("“practice the guitar”中 practice 后接（　）。", "名词或动名词", "动词原形", "to do", "过去式"),
            Q("“No smoking.”的意思是（　）。", "禁止吸烟", "没有烟", "不吸烟的人", "吸烟"),
            Q("“No + 动名词”表示（　）。", "禁止做某事", "没有做某事", "不去做某事", "做完某事"),
            Q("表达“不要把手机带到学校”应说（　）。", "Don't bring mobile phones to school.", "Don't bring mobile phones at school.", "Don't take mobile phones to the school.", "Don't bringing mobile phones to school."),
            Q("“bring”与“take”的区别是（　）。", "bring 带来，take 带走", "bring 带走，take 带来", "意思相同", "bring 用于人，take 用于物"),
            Q("“Do your homework after school.”是（　）句。", "肯定祈使", "否定祈使", "疑问", "感叹"),
        ]),
        ("第3课 综合运用", "Talk about family rules and school rules. 综合运用本单元内容谈论规则与建议。", [
            Q("介绍家规可以说（　）。", "I have to do my homework first after school.", "I have to doing my homework first after school.", "I have do my homework first after school.", "I has to do my homework first after school."),
            Q("“My parents don't allow me to play computer games on weekdays.”中 allow 的意思是（　）。", "允许", "大声说", "即使", "立刻"),
            Q("表达“我十点前必须上床睡觉”应说（　）。", "I have to go to bed before ten.", "I have to go to bed until ten.", "I have go to bed before ten.", "I has to go to bed before ten."),
            Q("“too many rules”中 many 修饰（　）。", "可数名词复数 rules", "不可数名词", "形容词", "动词"),
            Q("“I never have any fun.”中 fun 是（　）。", "不可数名词（乐趣）", "形容词", "动词", "可数名词"),
            Q("表达“周末我可以放松”应说（　）。", "On weekends I can relax.", "On weekends I can relaxing.", "On weekends I can to relax.", "On weekends I can relax to."),
            Q("“relax”的意思是（　）。", "放松", "休息处", "放松的", "放松地"),
            Q("“Don't leave the dirty dishes in the kitchen.”中 leave 的意思是（　）。", "留下", "离开（另一义）", " leaves 的原形", "离开地"),
            Q("“After dinner, I can't relax either.”中 either 用于（　）。", "否定句句末", "肯定句句末", "疑问句", "句首"),
            Q("“too”与“either”都表示“也”，区别是（　）。", "too 用于肯定句，either 用于否定句", "too 用于否定句，either 用于肯定句", "意思不同", "无区别"),
            Q("表达“学习前不能看电视”应说（　）。", "I can't watch TV before I finish my homework.", "I can't watch TV before I finish my homework to.", "I can't watch TV before finish my homework.", "I can't watch TV before I finishing my homework."),
            Q("“finish”后接（　）。", "动名词", "动词原形", "to do", "过去式"),
            Q("“There are too many rules in my life.”中 too many 的意思是（　）。", "太多（修饰可数名词）", "太多（修饰不可数名词）", "非常多", "太……以至于"),
            Q("“luckily”的意思是（　）。", "幸运地", "幸运的", "运气", "不幸地"),
            Q("表达“规则虽多但有用”应说（　）。", "There are many rules, but they are useful.", "There are many rules, but they are useful to.", "There is many rules, but they are useful.", "There are many rules, but they useful are."),
            Q("“obey the rules”的意思是（　）。", "遵守规则", "制定规则", "打破规则", "记住规则"),
            Q("表达“我们应当遵守校规”应说（　）。", "We should obey the school rules.", "We should obey school rule.", "We should obeying the school rules.", "We should to obey the school rules."),
            Q("“follow the rules”中 follow 的意思是（　）。", "遵循", "跟随某人走（另一义）", "以下", "follower 的原形"),
            Q("“safe”的意思是（　）。", "安全的", "储蓄罐", "安全地", "拯救"),
            Q("表达“过马路要走斑马线”应说（　）。", "Walk on the zebra crossing when you cross the road.", "Walk on the zebra crossing when you across the road.", "Walk on the zebra crossing when cross the road you.", "Walking on the zebra crossing when you cross road."),
            Q("“traffic rules”的意思是（　）。", "交通规则", "交通工具", "交通灯", "交通堵塞"),
            Q("表达“人人都要守规矩”可以说（　）。", "Everyone should follow the rules.", "Everyone should follow the rule.", "Everyone should follows the rules.", "Everyone should following the rules."),
        ]),
    ]),
    ("第三单元 Keep Fit", [
        ("第1课 核心词汇", "Today's words: exercise / healthy / junk food / sleep / strong / once。学会谈论健康生活习惯。", build_vocab([
            ("exercise", "锻炼"), ("healthy", "健康的"), ("junk food", "垃圾食品"),
            ("sleep", "睡觉"), ("strong", "强壮的"), ("once", "一次"),
            ("twice", "两次"), ("milk", "牛奶"), ("vegetable", "蔬菜"),
            ("fruit", "水果"), ("habit", "习惯"), ("body", "身体"),
        ])),
        ("第2课 句型与对话", "Sentences: How often do you exercise? / What's the matter? / You should drink more water. 学会谈论锻炼频率与健康建议。", [
            Q("询问“你多久锻炼一次？”应说（　）。", "How often do you exercise?", "How long do you exercise?", "How much do you exercise?", "How many do you exercise?"),
            Q("回答“每天”应说（　）。", "I exercise every day.", "I exercise everyday of.", "I exercise on every day.", "I exercising every day."),
            Q("回答“一周两次”应说（　）。", "I exercise twice a week.", "I exercise two times a week of.", "I exercise twice on a week.", "I exercise two a week."),
            Q("“how often”用来提问（　）。", "频率", "时长", "距离", "次数总和"),
            Q("“how long”用来提问（　）。", "多长时间或多长", "频率", "多久以后", "多少个"),
            Q("表达“多吃蔬菜对你有好处”应说（　）。", "Eating more vegetables is good for you.", "Eat more vegetables is good for you.", "Eating more vegetables are good for you.", "Eating much vegetables is good for you."),
            Q("“be good for”的意思是（　）。", "对……有好处", "擅长", "对……好（人好）", "好的于"),
            Q("“be bad for”的意思是（　）。", "对……有害", "坏的", "对……不好（人坏）", "害处的"),
            Q("表达“垃圾食品对你有害”应说（　）。", "Junk food is bad for you.", "Junk food is bad to you.", "Junk food are bad for you.", "Junk food is badly for you."),
            Q("“What's the matter?”的意思是（　）。", "你怎么了？", "什么事这么重要？", "你怎么做的？", "问题是啥？"),
            Q("回答“我头疼”应说（　）。", "I have a headache.", "I have a head ache of.", "I have headache.", "My head is pain."),
            Q("“have a cold”的意思是（　）。", "感冒", "冷的", "着凉的名词", "感冒药"),
            Q("“You should drink more water.”中 should 表示（　）。", "建议", "必须", "能够", "将要"),
            Q("“should”后接（　）。", "动词原形", "动名词", "to do", "过去式"),
            Q("表达“你应该去看医生”应说（　）。", "You should see a doctor.", "You should see the doctor to.", "You should to see a doctor.", "You should seeing a doctor."),
            Q("“I have a sore throat.”的意思是（　）。", "我嗓子疼。", "我喉咙痒。", "我嗓子哑了。", "我喉咙里有东西。"),
            Q("“lie down and rest”的意思是（　）。", "躺下休息", "躺下睡觉", "坐下来", "站起来"),
            Q("表达“不要太累”应说（　）。", "Don't be too tired.", "Don't be too tired to.", "Not be too tired.", "Don't too tired."),
            Q("“stay healthy”的意思是（　）。", "保持健康", "停留健康", "健康的", "恢复健康"),
            Q("“It's important to sleep well.”中 it 是（　）。", "形式主语", "真正主语", "宾语", "表语"),
            Q("表达“早睡早起身体好”应说（　）。", "Going to bed early and getting up early is good for your health.", "Go to bed early and get up early is good for your health.", "Going to bed early and getting up early are good for your health.", "Going to bed early and get up early is good for your health."),
            Q("“take exercise”的意思是（　）。", "进行锻炼", "拿走练习", "服用锻炼", "做练习"),
        ]),
        ("第3课 综合运用", "Talk about healthy living and a good lifestyle. 综合运用本单元内容谈健康生活。", [
            Q("健康的生活方式不包括（　）。", "熬夜打游戏", "均衡饮食", "坚持锻炼", "按时睡觉"),
            Q("“balanced diet”的意思是（　）。", "均衡饮食", "平衡木", "饮食文化", "节食"),
            Q("表达“他每周锻炼三次”应说（　）。", "He exercises three times a week.", "He exercise three times a week.", "He exercising three times a week.", "He exercises three time a week."),
            Q("“once a month”的意思是（　）。", "每月一次", "一个月里", "一次一月", "每月两次"),
            Q("表达“我很少吃垃圾食品”应说（　）。", "I hardly ever eat junk food.", "I hardly ever eats junk food.", "I hardly ever eating junk food.", "I hard ever eat junk food."),
            Q("“hardly ever”的意思是（　）。", "几乎不", "努力地", "几乎常常", "努力曾"),
            Q("“How many hours do you sleep every night?”的正确答句是（　）。", "I sleep eight hours.", "I sleep eight hour.", "I am sleep eight hours.", "I sleeping eight hours."),
            Q("表达“吸烟有害健康”应说（　）。", "Smoking is bad for your health.", "Smoking is bad for healthy.", "Smoke is bad for your health.", "Smoking is bad to your health."),
            Q("“health”与“healthy”的词性分别是（　）。", "名词与形容词", "形容词与名词", "都是名词", "都是形容词"),
            Q("表达“运动使我们更强壮”应说（　）。", "Exercise makes us stronger.", "Exercise makes us more strong.", "Exercise make us stronger.", "Exercise makes us strongest."),
            Q("“make + 宾语 + 形容词”表示（　）。", "使某人/某物处于某状态", "制作某物", "使做某事", "强迫做"),
            Q("表达“我们应该天天刷牙”应说（　）。", "We should brush our teeth every day.", "We should brush tooth every day.", "We should brushing our teeth every day.", "We should to brush our teeth every day."),
            Q("“wash hands before meals”的意思是（　）。", "饭前洗手", "饭后洗手", "洗手做早饭", "洗餐巾"),
            Q("表达“熬夜对你眼睛不好”应说（　）。", "Staying up late is bad for your eyes.", "Stay up late is bad for your eyes.", "Staying up late are bad for your eyes.", "Staying up late is bad at your eyes."),
            Q("“keep away from”的意思是（　）。", "远离", "保持离开", "远离的名词", "保留"),
            Q("表达“远离垃圾食品”应说（　）。", "Keep away from junk food.", "Keep away from junk food to.", "Keep away junk food.", "Keeping away from junk food."),
            Q("“a healthy lifestyle”的意思是（　）。", "健康的生活方式", "健康的生活习惯（同义，但 lifestyle 指方式）", "生活的健康", "生活的样式"),
            Q("表达“喝水对我们很重要”应说（　）。", "Drinking water is important to us.", "Drink water is important to us.", "Drinking water are important to us.", "Drinking water is important for we."),
            Q("“less”是 little 的比较级，意思是（　）。", "更少的（修饰不可数名词）", "更小的", "最少", "更少的（可数）"),
            Q("表达“少吃糖”应说（　）。", "Eat less sugar.", "Eat fewer sugar.", "Eat little sugar.", "Eat less sugars."),
            Q("“less sugar”与“fewer sweets”的区别是（　）。", "less 修饰不可数，fewer 修饰可数复数", "less 修饰可数，fewer 修饰不可数", "意思相同", "less 更正式"),
            Q("表达“健康是最大的财富”可以说（　）。", "Health is the greatest wealth.", "Healthy is the greatest wealth.", "Health are the greatest wealth.", "Health is the greater wealth."),
        ]),
    ]),
    ("第四单元 Eat Well", [
        ("第1课 核心词汇", "Today's words: dumpling / porridge / cabbage / beef / strawberry / juice。学会说出常见食物与饮料。", build_vocab([
            ("dumpling", "饺子"), ("porridge", "粥"), ("cabbage", "卷心菜"),
            ("beef", "牛肉"), ("strawberry", "草莓"), ("juice", "果汁"),
            ("noodle", "面条"), ("potato", "土豆"), ("tomato", "西红柿"),
            ("onion", "洋葱"), ("carrot", "胡萝卜"), ("pancake", "烙饼；薄煎饼"),
        ])),
        ("第2课 句型与对话", "Sentences: What would you like? / I'd like some noodles. / Would you like a large bowl? 学会在餐馆点餐。", [
            Q("服务员问“您想要点什么？”应说（　）。", "What would you like?", "What do you like eat?", "What would you like eat?", "What are you like?"),
            Q("回答“我想要一些面条”应说（　）。", "I'd like some noodles.", "I'd like some noodle.", "I'd like any noodles.", "I like some noodles."),
            Q("“I'd like”是“（　）”的缩写。", "I would like", "I had like", "I could like", "I should like"),
            Q("“Would you like some tea?”的肯定回答是（　）。", "Yes, please.", "Yes, I would like.", "Yes, I do.", "Yes, I like."),
            Q("“some”用于疑问句时表示（　）。", "希望得到肯定回答", "任何", "一些（任意）", "没有特殊含义"),
            Q("“a bowl of rice”的意思是（　）。", "一碗米饭", "一碗的米饭碗", "米饭碗", "一碗粥"),
            Q("“large”的意思是（　）。", "大的", "宽的", "高的", "长的"),
            Q("“medium”的意思是（　）。", "中等的", "媒质", "中间人", "平均的"),
            Q("“small”的反义词是（　）。", "large", "short", "thin", "low"),
            Q("“What kind of noodles would you like?”的意思是（　）。", "你想要哪种面条？", "你要多少面条？", "你的面条多少钱？", "你喜欢面条吗？"),
            Q("回答 What kind of noodles would you like? 可以说（　）", "I'd like beef noodles, please.", "I'd like beef noodle, please.", "I'd like beefs noodles, please.", "I'd like to beef noodles."),
            Q("“potato”的复数形式是（　）。", "potatoes", "potatos", "potatoe", "potatoss"),
            Q("“tomato”的复数形式是（　）。", "tomatoes", "tomatos", "tomatoe", "tomatoies"),
            Q("表达“请给我菜单”应说（　）。", "May I have the menu, please?", "May I have menu, please?", "May I have a menu, please?（语境均可，标准为 the menu）", "Give I the menu."),
            Q("“order”在餐馆语境中意思是（　）。", "点菜；订购", "顺序", "命令", "订货单"),
            Q("表达“你想喝点什么”应说（　）。", "What would you like to drink?", "What would you like drink?", "What would you like drinking?", "What would you drink like?"),
            Q("“green tea”的意思是（　）。", "绿茶", "绿色的茶杯", "茶叶", "红茶"),
            Q("表达“还要别的吗”应说（　）。", "Anything else?", "Something else?", "Any else thing?", "Else anything?"),
            Q("“Here's the menu.”中 Here's 是（　）。", "Here is 的缩写", "Here has 的缩写", "Here was 的缩写", "Here are 的缩写"),
            Q("“The beef is delicious.”中 delicious 的意思是（　）。", "美味的", "昂贵的", "新鲜的", "可口的汤"),
            Q("“Enjoy your meal!”的意思是（　）。", "请慢慢享用！", "享受你的餐点名字", "饭好吃吗？", "吃完了！"),
            Q("“bill”在餐馆语境中意思是（　）。", "账单", "比尔（人名）", "钞票（另一义）", " poster 的同义"),
        ]),
        ("第3课 综合运用", "Order food and talk about eating habits. 综合运用本单元内容点餐与谈论饮食习惯。", [
            Q("点餐时的礼貌用语常以（　）开头。", "Would you like ... / May I have ...", "Give me ...", "I want ...", "You should ..."),
            Q("表达“我想要一杯橙汁”应说（　）。", "I'd like a glass of orange juice.", "I'd like a glass orange juice.", "I'd like a glass of orange juices.", "I'd like an orange juice of glass."),
            Q("“a cup of tea”中 cup 指的是（　）。", "一杯（的量）", "茶杯（仅指容器）", "茶壶", "茶"),
            Q("表达“这条鱼很好吃”应说（　）。", "The fish tastes delicious.", "The fish tastes deliciously.", "The fish taste delicious.", "The fish is taste delicious."),
            Q("“taste”在此处是（　）。", "系动词", "实义动词", "助动词", "情态动词"),
            Q("“sweet”的意思是（　）。", "甜的", "糖果（另一义）", "汗水", "馊的"),
            Q("“sour”的意思是（　）。", "酸的", "甜的", "苦的", "辣的"),
            Q("“salty”的意思是（　）。", "咸的", "盐", "甜的", "酸的"),
            Q("“spicy”的意思是（　）。", "辣的", "香的", "咸的", "酸的"),
            Q("表达“我不吃辣”应说（　）。", "I don't eat spicy food.", "I don't eat spice food.", "I not eat spicy food.", "I don't eats spicy food."),
            Q("“Is there any beef in the noodles?”中 any 用于（　）。", "疑问句", "肯定句", "祈使句", "感叹句"),
            Q("回答“有一些”应说（　）。", "Yes, there is some.", "Yes, there is any.", "Yes, there are some.", "Yes, there is some beefs."),
            Q("表达“再来一份好吗”应说（　）。", "Could we have one more, please?", "Could we have one more, please to?", "Could we have one more please of?", "Could we having one more, please?"),
            Q("“help yourself”的意思是（　）。", "请随意（自己动手）", "帮助你自己", "自助餐", "自我帮助"),
            Q("表达“多吃水果和蔬菜”应说（　）。", "Eat more fruit and vegetables.", "Eat more fruits and vegetable.", "Eat much fruit and vegetables.", "Eating more fruit and vegetable."),
            Q("“That's all. Thank you.”用于（　）。", "点餐结束时", "开始点餐时", "道歉时", "告别时"),
            Q("“check, please”的意思是（　）。", "请结账", "请核对", "请检查我", "支票"),
            Q("表达“这顿饭我请客”应说（　）。", "It's my treat.", "It's my treat to.", "It's me treat.", "It's my treating."),
            Q("“junk food”指的是（　）。", "高油高糖低营养的食品", "垃圾桶里的食品", "垃圾场食品", "过期食品"),
            Q("表达“早餐很重要”应说（　）。", "Breakfast is very important.", "Breakfast are very important.", "Breakfast is very import.", "The breakfast is very important."),
            Q("“food”作食物总称时是（　）。", "不可数名词", "可数名词", "只用复数", "专有名词"),
            Q("表达“我饿了”应说（　）。", "I'm hungry.", "I'm hunger.", "I have hungry.", "I'm a hunger."),
        ]),
    ]),
    ("第五单元 Here and Now", [
        ("第1课 核心词汇", "Today's words: clean / read a newspaper / soup / wash / use / miss。学会描述正在进行的动作。", build_vocab([
            ("clean", "打扫"), ("read a newspaper", "看报纸"), ("soup", "汤"),
            ("wash", "洗"), ("use", "使用"), ("miss", "怀念；错过"),
            ("house", "房子"), ("drink tea", "喝茶"), ("young", "年轻的"),
            ("child", "孩子"), ("shop", "购物；商店"), ("pool", "游泳池"),
        ])),
        ("第2课 句型与对话", "Sentences: What are you doing? / I'm watching TV. / Is he doing his homework? 学会用现在进行时描述正在做的事。", [
            Q("询问“你正在做什么？”应说（　）。", "What are you doing?", "What do you do?", "What are you do?", "What you are doing?"),
            Q("回答“我正在看电视”应说（　）。", "I'm watching TV.", "I watch TV.", "I am watch TV.", "I'm watch TV."),
            Q("现在进行时的构成是（　）。", "be + 动词的 ing 形式", "动词 + ing", "do + ing", "be + 动词原形"),
            Q("“making”的正确构成是因为（　）。", "以不发音 e 结尾去 e 加 ing", "直接加 ing", "双写 m 加 ing", "变 y 为 i 加 ing"),
            Q("“running”的正确构成是因为（　）。", "重读闭音节双写末尾字母加 ing", "直接加 ing", "去 e 加 ing", "变 y 为 i 加 ing"),
            Q("“swim”的现在分词是（　）。", "swimming", "swiming", "swim", "swimeing"),
            Q("“write”的现在分词是（　）。", "writing", "writeing", "writting", "writ"),
            Q("“Is he doing his homework?”的肯定回答是（　）。", "Yes, he is.", "Yes, he does.", "Yes, he is doing.", "Yes, he can."),
            Q("“They are cleaning the classroom.”的意思是（　）。", "他们正在打扫教室。", "他们经常打扫教室。", "他们打扫了教室。", "他们将打扫教室。"),
            Q("“listen”的现在分词是（　）。", "listening", "listenning", "listen", "listenying"),
            Q("“What is she doing now?”中 now 表示（　）。", "现在（进行时标志）", "现在（时间点，但常与一般现在时）", "立刻", "现在（过去）"),
            Q("“We are having an English class.”的意思是（　）。", "我们正在上英语课。", "我们上英语课。", "我们将上英语课。", "我们上过英语课。"),
            Q("“drink”的现在分词是（　）。", "drinking", "drinking 与 drink 均可", "drinkking", "drunk"),
            Q("表达“他正在给朋友写信”应说（　）。", "He is writing a letter to his friend.", "He is writing a letter for his friend.", "He writes a letter to his friend now.", "He is writeing a letter to his friend."),
            Q("“play”的现在分词是（　）。", "playing", "playeing", "playying", "play"),
            Q("“Where are you going?”的意思是（　）。", "你要去哪里？（正在进行的动作）", "你去过哪里？", "你住在哪里？", "你从哪里来？"),
            Q("“I'm shopping in the supermarket.”的意思是（　）。", "我正在超市购物。", "我常在超市购物。", "我去超市购物了。", "我想去超市购物。"),
            Q("“talk on the phone”的意思是（　）。", "打电话", "在电话机旁", "挂断电话", "接电话的人"),
            Q("表达“妈妈正在做饭”应说（　）。", "Mom is cooking in the kitchen.", "Mom cooks in the kitchen now.", "Mom is cook in the kitchen.", "Mom is cooking at the kitchen."),
            Q("“in the kitchen”的意思是（　）。", "在厨房", "在厨房里做饭", "厨房", "厨房的"),
            Q("“study”的现在分词是（　）。", "studying", "studyeng", "studing", "studying 与 study 均可"),
            Q("“Are they watching TV or doing homework?”中 or 连接（　）。", "两个并列的现在分词", "两个动词原形", "两个过去式", "两个不定式"),
        ]),
        ("第3课 综合运用", "Describe a scene and what people are doing. 综合运用本单元内容描述场景。", [
            Q("描述照片场景时常用（　）。", "现在进行时", "一般现在时", "一般过去时", "一般将来时"),
            Q("“In the park, some people are dancing.”的意思是（　）。", "公园里有些人在跳舞。", "公园里有些人跳舞。", "公园里有些人将跳舞。", "公园里有人跳过舞。"),
            Q("“What are they waiting for?”中 wait for 的意思是（　）。", "等待", "等着（名词）", "服务", "观看"),
            Q("表达“他们在等公交车”应说（　）。", "They are waiting for the bus.", "They are waiting the bus.", "They wait for the bus now.", "They are waiting to the bus."),
            Q("“look at”与“see”的区别是（　）。", "look at 强调动作，see 强调结果", "意思相同", "look at 强调结果", "see 是进行时常用词"),
            Q("“Listen! Someone is singing.”中 Listen! 提示（　）。", "进行时", "一般时", "过去时", "将来时"),
            Q("“Look! The children are swimming.”中 Look! 提示（　）。", "进行时", "一般时", "过去时", "将来时"),
            Q("表达“那个男孩正在拍照”应说（　）。", "The boy is taking photos.", "The boy takes photos now.", "The boy is takeing photos.", "The boy is take photos."),
            Q("“take photos”的同义表达是（　）。", "take pictures", "make photos", "do pictures", "give photos"),
            Q("“Some are reading, others are writing.”中 others 指（　）。", "另一些人（不是全部剩余）", "其余全部的人", "其他人（泛指）", "另一个"),
            Q("表达“她在给花浇水”应说（　）。", "She is watering the flowers.", "She is watering the flowers to.", "She waters the flowers now.", "She is water the flowers."),
            Q("“water”在此作（　）。", "动词（浇水）", "名词（水）", "形容词", "副词"),
            Q("“The wind is blowing.”的意思是（　）。", "风正在吹。", "风吹过。", "风很大吗？", "风将吹来。"),
            Q("表达“大家玩得很开心”应说（　）。", "Everyone is having a good time.", "Everyone is having good time.", "Everyone having a good time.", "Everyone is have a good time."),
            Q("“have a good time”的同义短语是（　）。", "have fun", "have a fun", "have the fun", "having fun"),
            Q("“What a beautiful day!”是（　）句。", "感叹", "疑问", "祈使", "陈述"),
            Q("表达“一位老人正坐在长椅上看报纸”应说（　）。", "An old man is sitting on the bench reading a newspaper.", "An old man is sitting on the bench and reading newspaper.", "An old man sitting on the bench is reading a newspaper.（也正确但首选分词结构一般不作初一下重点）", "An old man is sit on the bench reading a newspaper."),
            Q("“bench”的意思是（　）。", "长椅", "长凳（同义，多指公园长凳）", "桌子", "椅子"),
            Q("表达“不要在教室里跑”应说（　）。", "Don't run in the classroom.", "Don't running in the classroom.", "Not run in the classroom.", "Don't to run in the classroom."),
            Q("“quietly”是形容词 quiet 的（　）。", "副词形式", "名词形式", "比较级", "反义词"),
            Q("表达“孩子们正安静地读书”应说（　）。", "The children are reading quietly.", "The children are reading quiet.", "The children are quiet reading.", "The children quiet are reading."),
            Q("“It's raining now.”中 rain 作（　）。", "动词（下雨）", "名词（雨）", "形容词", "副词"),
        ]),
    ]),
    ("第六单元 Rain or Shine", [
        ("第1课 核心词汇", "Today's words: rain / snow / windy / cloudy / sunny / weather。学会描述天气。", build_vocab([
            ("rain", "雨；下雨"), ("snow", "雪；下雪"), ("windy", "有风的"),
            ("cloudy", "多云的"), ("sunny", "晴朗的"), ("weather", "天气"),
            ("foggy", "有雾的"), ("rainy", "下雨的"), ("snowy", "下雪的"),
            ("hot", "热的"), ("cold", "冷的"), ("warm", "温暖的"),
        ])),
        ("第2课 句型与对话", "Sentences: How's the weather? / It's raining. / What's the weather like in ...? 学会询问与描述天气。", [
            Q("询问“天气怎么样？”应说（　）。", "How's the weather?", "What's the weather?", "How is the weather like?", "What the weather is?"),
            Q("同义问句是（　）。", "What's the weather like?", "What does the weather like?", "How does the weather like?", "Which is the weather like?"),
            Q("回答“正在下雨”应说（　）。", "It's raining.", "It's rainy.（另一说法，描述天气特征）", "It rain.", "It's rain."),
            Q("“It's sunny today.”的意思是（　）。", "今天天气晴朗。", "今天有太阳的人。", "今天很热。", "今天阴天。"),
            Q("“cloudy”的意思是（　）。", "多云的", "云", "下雨的", "有风的"),
            Q("“windy”的名词是（　）。", "wind", "winding", "windy 名词无", "winded"),
            Q("“snow”作动词时意思是（　）。", "下雪", "雪", "雪人", "下雪地"),
            Q("表达“北京天气怎么样”应说（　）。", "How's the weather in Beijing?", "How's the weather at Beijing?", "What's the weather like at Beijing?", "How's the weather on Beijing?"),
            Q("“It's cold and snowy.”的意思是（　）。", "天气寒冷多雪。", "天气冷雪人。", "天气冷且晴。", "天冷要下雪了。"),
            Q("询问“你最喜欢什么天气？”应说（　）。", "What weather do you like best?", "What weather you like best?", "Which weather do you like the best?", "How weather do you like best?"),
            Q("回答 What weather do you like best? 可以说（　）", "I like sunny days best.", "I like sunny day best.", "I like sunny days best to.", "I like sunniest days best."),
            Q("“rainy”与“raining”的区别是（　）。", "rainy 是形容词，raining 是现在分词", "意思相同", "rainy 是动词，raining 是形容词", "无区别"),
            Q("“What a heavy rain!”中 rain 是（　）。", "名词", "动词", "形容词", "副词"),
            Q("表达“明天会下雨”应说（　）。", "It will rain tomorrow.", "It will rainy tomorrow.", "It will raining tomorrow.", "It wills rain tomorrow."),
            Q("“put on”的意思是（　）。", "穿上（动作）", "穿着（状态）", "戴上（另一义同动作）", "放上去"),
            Q("“wear”的意思是（　）。", "穿着（状态）", "穿上（动作）", "磨损", "穿的名词"),
            Q("表达“外面很冷，穿上外套”应说（　）。", "It's cold outside. Put on your coat.", "It's cold outside. Wear on your coat.", "It's cold outside. Put up your coat.", "It's cold outside. Put your coat on it."),
            Q("“take an umbrella”的意思是（　）。", "带把伞", "买把伞", "撑开伞", "收伞"),
            Q("“umbrella”的读音重点是（　）。", "重音在第二音节", "重音在第一音节", "重音在第三音节", "无重音"),
            Q("表达“雨下得很大”应说（　）。", "It's raining heavily.", "It's raining heavy.", "It's raining hardly.", "It's heavily rain."),
            Q("“in the rain”的意思是（　）。", "在雨中", "在雨天（日期）", "下雨时（时间）", "雨伞下"),
            Q("“wind”的意思是（　）。", "风", "窗户", "冬天", "缠绕"),
            Q("“fog”的意思是（　）。", "雾", "烟雾", "霜", "露水"),
        ]),
        ("第3课 综合运用", "Talk about weather, seasons and activities. 综合运用本单元内容谈论天气与季节活动。", [
            Q("四季的说法是（　）。", "spring, summer, autumn/fall, winter", "spring, summer, autumn, winterly", "spring, summer, autumn, winter 的缩写 s/s/a/w", "spr, sum, aut, win"),
            Q("“spring”的意思是（　）。", "春天；泉水", "弹簧（另一义）", "跳", "春季地"),
            Q("表达“夏天很热”应说（　）。", "It's hot in summer.", "It's hot on summer.", "It's hot at summer.", "It's hot in the summer of."),
            Q("“What do you do on rainy days?”的意思是（　）。", "下雨天你做什么？", "雨天你喜欢什么？", "雨天你去哪里？", "雨天下雨吗？"),
            Q("回答 What do you do on rainy days? 可以说（　）", "I usually read books at home.", "I usually reading books at home.", "I usually read book at home.", "I usually read books in home."),
            Q("“snowman”的意思是（　）。", "雪人", "下雪的人", "雪中的人", "雪地"),
            Q("表达“我们可以堆雪人”应说（　）。", "We can make a snowman.", "We can make snowman.", "We can making a snowman.", "We can make a snow man of."),
            Q("“best season”的意思是（　）。", "最喜欢的季节", "最好的季节（同义，但语境不同）", "好的季节", "最好季节的"),
            Q("表达“春天万物复苏”可以说（　）。", "In spring, everything comes back to life.", "In spring, everything comes back to life to.", "In spring, everything come back to life.", "In spring, everything is coming back to the life."),
            Q("“come back to life”的意思是（　）。", "复苏", "回到生活", "回到生命中", "活过来吗"),
            Q("“The weather is different in different places.”的意思是（　）。", "不同地方天气不同。", "不同天气在不同地方。", "天气在变化。", "各地天气相同。"),
            Q("表达“今天比昨天冷”应说（　）。", "It's colder today than yesterday.", "It's more cold today than yesterday.", "It's cold today than yesterday.", "It's colder today that yesterday."),
            Q("“colder”是（　）。", "cold 的比较级", "cold 的最高级", "cold 的原级", "colds 的单数"),
            Q("表达“今天是最热的一天”应说（　）。", "It's the hottest day today.", "It's the most hot day today.", "It's hotter day today.", "It's hotest day today."),
            Q("“hot”的最高级是（　）。", "hottest", "hotest", "most hot", "hots"),
            Q("“warm”的反义词是（　）。", "cool", "cold", "hot", "warmly"),
            Q("“cool”的意思是（　）。", "凉爽的", "冷的", "暖和的", "酷的名词"),
            Q("表达“雨后天上有彩虹”应说（　）。", "There is a rainbow after the rain.", "There is a rainbow after rain.", "There are a rainbow after the rain.", "There is the rainbow after a rain."),
            Q("“rainbow”的意思是（　）。", "彩虹", "雨弓", "雨衣", "雨靴"),
            Q("表达“天气预报说明天有风”应说（　）。", "The weather report says it will be windy tomorrow.", "The weather report says it will windy tomorrow.", "The weather report say it will be windy tomorrow.", "The weather report says it will be wind tomorrow."),
            Q("“weather report”的意思是（　）。", "天气预报", "天气报告员", "天气报告单", "报告天气"),
            Q("表达“雨天请小心路滑”可以说（　）。", "Be careful, the road is wet on rainy days.", "Be careful, the road is wet on rain days.", "Be careful, the road are wet on rainy days.", "Be careful, the road is wet on the rainy."),
        ]),
    ]),
    ("第七单元 A Day to Remember", [
        ("第1课 核心词汇", "Today's words: visit / museum / gift / delicious / take photos / exciting。学会描述难忘的经历。", build_vocab([
            ("visit", "参观；拜访"), ("museum", "博物馆"), ("gift", "礼物"),
            ("delicious", "美味的"), ("take photos", "拍照"), ("exciting", "令人兴奋的"),
            ("trip", "旅行"), ("beach", "海滩"), ("camp", "露营"),
            ("mountain", "山"), ("photo", "照片"), ("wonderful", "精彩的"),
        ])),
        ("第2课 句型与对话", "Sentences: What did you do last weekend? / I visited my grandparents. / Did you have fun? 学会用一般过去时谈过去的经历。", [
            Q("询问“上周末你做了什么？”应说（　）。", "What did you do last weekend?", "What do you do last weekend?", "What did you did last weekend?", "What was you do last weekend?"),
            Q("回答“我去看望了祖父母”应说（　）。", "I visited my grandparents.", "I visit my grandparents.", "I was visit my grandparents.", "I visits my grandparents."),
            Q("一般过去时表示（　）。", "过去发生的动作或状态", "经常发生的动作", "正在进行的动作", "将要发生的动作"),
            Q("“go”的过去式是（　）。", "went", "goed", "gone", "going"),
            Q("“visit”的过去式是（　）。", "visited", "visitted", "visit", "visiting"),
            Q("“do”的过去式是（　）。", "did", "done", "does", "doing"),
            Q("“take”的过去式是（　）。", "took", "taked", "taken", "taking"),
            Q("“eat”的过去式是（　）。", "ate", "eated", "eaten", "eating"),
            Q("“have”的过去式是（　）。", "had", "haved", "has", "having"),
            Q("“Did you have fun?”的肯定回答是（　）。", "Yes, I did.", "Yes, I had.", "Yes, I do.", "Yes, I was."),
            Q("“It was exciting.”中 exciting 的意思是（　）。", "令人兴奋的", "兴奋的（主语为人时多用 excited）", "兴奋地", "兴奋"),
            Q("表达“我们拍了很多照片”应说（　）。", "We took a lot of photos.", "We takeed a lot of photos.", "We take a lot of photos.", "We taked lots of photos."),
            Q("“a lot of”可以修饰（　）。", "可数名词复数或不可数名词", "只可数名词", "只不可数名词", "动词"),
            Q("“Where did you go?”的回答是（　）。", "I went to the museum.", "I go to the museum.", "I was go to the museum.", "I did go the museum."),
            Q("“buy”的过去式是（　）。", "bought", "buyed", "buied", "boughten"),
            Q("表达“我给妹妹买了礼物”应说（　）。", "I bought a gift for my sister.", "I bought a gift to my sister.", "I buyed a gift for my sister.", "I bought a gift for my sister to."),
            Q("“see”的过去式是（　）。", "saw", "seed", "seen", "seeing"),
            Q("“How was your trip?”的回答是（　）。", "It was wonderful.", "It is wonderful.", "It were wonderful.", "It wonderful."),
            Q("“last week”的意思是（　）。", "上周", "最后一周", "下周", "这周"),
            Q("“yesterday”的意思是（　）。", "昨天", "明天", "前天", "今天"),
            Q("“the day before yesterday”的意思是（　）。", "前天", "昨天", "后天", "大后天"),
            Q("“just now”的意思是（　）。", "刚才", "现在", "刚刚好", "片刻"),
        ]),
        ("第3课 综合运用", "Write about a memorable day. 综合运用本单元内容写难忘的一天。", [
            Q("写“难忘的一天”通常用（　）时态。", "一般过去时", "一般现在时", "现在进行时", "一般将来时"),
            Q("“It was a day to remember.”的意思是（　）。", "那是难忘的一天。", "那一天要记住它。", "那天会过去。", "那是纪念的一天。"),
            Q("表达“我们上周去了海滩”应说（　）。", "We went to the beach last week.", "We go to the beach last week.", "We was go to the beach last week.", "We goed to the beach last week."),
            Q("“swim”的过去式是（　）。", "swam", "swimed", "swum（完成时用）", "swimming"),
            Q("表达“我们在海边游泳”应说（　）。", "We swam in the sea.", "We swimmed in the sea.", "We swim in the sea.", "We swam on the sea."),
            Q("“camp”作动词时意思是（　）。", "露营", "营地", "野营用的帐篷", "阵营"),
            Q("表达“我们去山里露营了”应说（　）。", "We camped in the mountains.", "We camped on the mountains.", "We camp in the mountains.", "We camping in the mountains."),
            Q("“get up early”的过去式表达是（　）。", "got up early", "getted up early", "got up earlyly", "get up early"),
            Q("“get”的过去式是（　）。", "got", "getted", "gotten（美式完成时）", "gets"),
            Q("表达“那天的日落很美”应说（　）。", "The sunset was beautiful that day.", "The sunset is beautiful that day.", "The sunset were beautiful that day.", "The sunset was beautiful on that day."),
            Q("“sunset”的意思是（　）。", "日落", "日出", "阳光", "日光"),
            Q("“sunrise”的意思是（　）。", "日出", "日落", "阳光", "防晒"),
            Q("表达“我真开心”应说（　）。", "I was so happy.", "I am so happy.（时态不符）", "I was so happily.", "I were so happy."),
            Q("“unforgettable”的意思是（　）。", "难忘的", "不忘记", "忘却的", "难懂的"),
            Q("表达“我永远不会忘记那一天”应说（　）。", "I will never forget that day.", "I will never forget that day to.", "I will never forgot that day.", "I won't never forget that day."),
            Q("“forget”的过去式是（　）。", "forgot", "forgetted", "forgotten（完成时用）", "forgeting"),
            Q("“It was the best day of my life.”中最高级 the best 表示（　）。", "最好的", "更好", "好", "最好地"),
            Q("表达“那是我最好的一次旅行”应说（　）。", "It was my best trip.", "It was my better trip.", "It was my goodest trip.", "It was the my best trip."),
            Q("“come back”的过去式是（　）。", "came back", "comed back", "come backed", "comes back"),
            Q("表达“我们下午回家了”应说（　）。", "We came back home in the afternoon.", "We come back home in the afternoon.", "We came back to home in the afternoon.", "We came to back home in the afternoon."),
            Q("“in the afternoon”与“on that afternoon”的区别是（　）。", "泛指用 in，特指某天用 on", "意思完全相同", "泛指用 on，特指用 in", "没有区别"),
            Q("“remember”的反义词是（　）。", "forget", "remember me", "memory", "remind"),
        ]),
    ]),
    ("第八单元 复习与检测", [
        ("第1课 Revision 1 综合复习一", "Review Units 1-4: animals, rules, health, food.", [
            Q("“Why do you like pandas?”的回答要用（　）引导。", "Because", "So", "But", "And"),
            Q("“Don't arrive late for class.”是（　）句。", "否定祈使", "肯定祈使", "疑问", "感叹"),
            Q("“have to”的否定形式是（　）。", "don't have to", "have not to", "doesn't have to（主语三单时）", "mustn't（含义不同）"),
            Q("“How often”回答通常是（　）。", "every day / twice a week 等", "for two hours", "three kilometers", "at six"),
            Q("“What would you like?”中 would like 表示（　）。", "想要（委婉）", "将要喜欢", "过去喜欢", "愿意地"),
            Q("“some”与“any”的区别是（　）。", "some 常用于肯定句，any 常用于疑问和否定", "some 用于疑问，any 用于肯定", "可以互换", "some 修饰可数，any 修饰不可数"),
            Q("“potatoes”复数加 es 因为（　）。", "以 o 结尾的某些名词加 es", "所有以 o 结尾都加 es", "以 s 结尾加 es", "无规则"),
            Q("“be bad for”的意思是（　）。", "对……有害", "坏的", "对……不好", "有害地"),
            Q("“You should see a dentist.”的意思是（　）。", "你应该看牙医。", "你应该当牙医。", "你应该请牙医来。", "你应该谢谢牙医。"),
            Q("“ dentist ”的中文意思是（　）。", "牙医", "医生", "兽医", "护士"),
            Q("“What's the matter with you?”的同义句是（　）。", "What's wrong with you?", "What's the wrong of you?", "What matter is you?", "How matter you?"),
            Q("“The elephant is from Thailand.”的意思是（　）。", "大象来自泰国。", "大象在泰国。", "大象去泰国。", "大象喜欢泰国。"),
            Q("“We have to keep quiet in the library.”的否定是（　）。", "We don't have to keep quiet in the library.", "We have to not keep quiet in the library.", "We have to keep not quiet in the library.", "We haven't to keep quiet in the library."),
            Q("“orange juice”的意思是（　）。", "橙汁", "橙色的果汁杯", "橘子酱", "橙树"),
            Q("“How much is the milk?”是询问（　）。", "价格", "数量", "频度", "距离"),
            Q("“Eating vegetables is good for us.”的主语是（　）。", "动名词短语", "动词", "形容词", "副词"),
            Q("“Don't talk loudly in class.”中 loudly 是（　）。", "副词", "形容词", "名词", "动词"),
            Q("“I'd like a medium bowl.”的意思是（　）。", "我要一个中碗。", "我要一个中号碗的碗。", "我要中等的。", "我要大碗。"),
            Q("“What kind of dumplings would you like?”中 kind 的意思是（　）。", "种类", "善良的", "种类（动词）", " kindly 的原形"),
            Q("“Animals are losing their homes.”中 homes 指（　）。", "栖息地", "家庭", "房子", "家乡"),
            Q("“We should protect the animals.”中 should 后接（　）。", "动词原形", "动名词", "to do", "过去式"),
            Q("“Go to bed early”的同义句是（　）。", "Sleep early", "Sleep early to", "Sleeping early", "Early sleep"),
        ]),
        ("第2课 Revision 2 综合复习二", "Review Units 5-7: present continuous, weather, past events.", [
            Q("现在进行时“be + v-ing”中 be 随（　）变化。", "主语", "时间", "动词", "宾语"),
            Q("“They are playing soccer now.”的否定句是（　）。", "They aren't playing soccer now.", "They don't playing soccer now.", "They are not play soccer now.", "They aren't play soccer now."),
            Q("“run”的现在分词是（　）。", "running", "runing", "run", "runned"),
            Q("“How's the weather in summer?”的回答可以是（　）。", "It's hot.", "It's hot to.", "It's heat.", "It hot."),
            Q("“It's raining.”中的 It 指（　）。", "天气", "它（物）", "那个人", "时间"),
            Q("“What's the weather like?”的同义句是（　）。", "How's the weather?", "What does the weather?", "How is like the weather?", "What the weather like?"),
            Q("“Yesterday”是一般过去时的（　）。", "标志词", "现在时词", "将来时词", "进行时词"),
            Q("“I did my homework last night.”的疑问句是（　）。", "Did you do your homework last night?", "Did you did your homework last night?", "Do you did your homework last night?", "Was you do your homework last night?"),
            Q("“read”的过去式是（　）。", "read（发音变化）", "readed", "read 的过去式写作 read，发音 /red/", "reads"),
            Q("“It was sunny yesterday.”的疑问句是（　）。", "Was it sunny yesterday?", "Did it sunny yesterday?", "Is it sunny yesterday?", "Was it sun yesterday?"),
            Q("“There was a heavy rain last night.”的意思是（　）。", "昨晚下了一场大雨。", "昨晚有大雨吗？", "昨晚要下雨。", "昨晚没下雨。"),
            Q("“beach”的复数是（　）。", "beaches", "beachs", "beachies", "beach"),
            Q("“We had great fun at the party.”中 fun 是（　）。", "不可数名词", "可数名词", "形容词", "副词"),
            Q("“took”是（　）的过去式。", "take", "took", "talk", "take 的过去分词 taken"),
            Q("“What did you see in the museum?”的回答是（　）。", "I saw many old things.", "I see many old things.", "I was see many old things.", "I saw many old thing."),
            Q("“It's time to go home.”的同义句是（　）。", "It's time for home.", "It's time to home.", "It's time go home.", "It's time for go home."),
            Q("“They enjoyed themselves at the party.”中 enjoyed themselves 意思是（　）。", "玩得开心", "享受他们自己", "玩自己", "喜欢自己"),
            Q("“have a good time”中可以用（　）替换。", "enjoy oneself", "enjoy themselves themselves", "enjoy oneselves", "have a fun"),
            Q("“I went there by train.”的意思是（　）。", "我坐火车去的。", "我坐火车去那里吗？", "火车去那里。", "我去火车站。"),
            Q("“photo”的复数是（　）。", "photos", "photoes", "photoss", "photo"),
            Q("“What an exciting trip!”是（　）句。", "感叹", "疑问", "祈使", "陈述"),
            Q("“We'll never forget this day.”中 will 表示（　）。", "将来", "意愿（另一义）", "将（物主）", "将来地"),
        ]),
    ]),
]

if __name__ == "__main__":
    run(r"content/middle/pep/grade1/volume2/english", "英语下册", UNITS)
